function k(a,b,c,d){a.u.nb(a.Pb,b,c,d,void 0)}function aa(a,b,c,d){a.u.pa?k(a,b,c,d):a.u.pf()._OnMessageFromDOM({type:"event",component:a.Pb,handler:b,dispatchOpts:d||null,data:c,responseId:null})}function ba(a,b,c){a.u.K(a.Pb,b,c)}function ca(a,b){for(const [c,d]of b)ba(a,c,d)}function da(a){a.vc||(a.u.Sd(a.ze),a.vc=!0)}window.lb=class{constructor(a,b){this.u=a;this.Pb=b;this.vc=!1;this.ze=()=>this.pb()}Id(){}pb(){}};function ea(a){-1!==a.Fd&&(self.clearTimeout(a.Fd),a.Fd=-1)}
window.dg=class{constructor(){this.Fd=-1;this.Df=!1}Rd(){this.Df||ea(this)}j(){ea(this)}};"use strict";function fa(a,b){ba(a,"get-element",c=>{const d=m(a,c.elementId);return b(d,c)})}function m(a,b){a=a.tc.get(b);if(!a)throw Error(`no element with id ${b}`);return a.ce}
window.cg=class extends self.lb{constructor(a,b){super(a,b);this.tc=new Map;this.kd=!0;ca(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=m(this,c);this.kd&&d.parentElement.removeChild(d);this.tc.delete(c)}],["set-visible",c=>{if(this.kd){var d=this.tc.get(c.elementId),e=d.ce;d.ie?e.style.display=c.isVisible?"":"none":d.Ff=!!c.isVisible}}],["update-position",c=>{if(this.kd){var d=this.tc.get(c.elementId),e=d.ce;e.style.left=c.left+"px";e.style.top=c.top+
"px";e.style.width=c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.ie||(d.ie=!0,d.Ff&&(e.style.display=""))}}],["update-state",c=>{m(this,c.elementId);throw Error("required override");}],["focus",c=>this.ed(c)],["set-css-style",c=>{const d=m(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{m(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{m(this,c.elementId).removeAttribute(c.name)}]]);
fa(this,c=>c)}ed(a){var b=m(this,a.elementId);a.focus?b.focus():b.blur()}};"use strict";const ha=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),ia=/android/i.test(navigator.userAgent),ja=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ka=0;
function la(a){const b=document.createElement("script");b.async=!1;b.type="module";return a.Qf?new Promise(c=>{const d="c3_resolve_"+ka;++ka;self[d]=c;b.textContent=a.Xf+`\n\nself["${d}"]();`;document.head.appendChild(b)}):new Promise((c,d)=>{b.onload=c;b.onerror=d;b.src=a;document.head.appendChild(b)})}let ma=!1,na=!1;function oa(){if(!ma){try{new Worker("blob://",{get type(){na=!0}})}catch(a){}ma=!0}return na}let n=new Audio;
const pa={"audio/webm; codecs=opus":!!n.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!n.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!n.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!n.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!n.canPlayType("audio/mp4"),"audio/mpeg":!!n.canPlayType("audio/mpeg")};n=null;async function qa(a){a=await ra(a);return(new TextDecoder("utf-8")).decode(a)}
function ra(a){return new Promise((b,c)=>{const d=new FileReader;d.onload=e=>b(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(a)})}const sa=[];let ta=0;window.RealFile=window.File;const ua=[],va=new Map,wa=new Map;let xa=0;const ya=[];self.runOnStartup=function(a){if("function"!==typeof a)throw Error("runOnStartup called without a function");ya.push(a)};const za=new Set(["cordova","playable-ad","instant-games"]);let Aa=!1;
window.Ra=class a{constructor(b){this.pa=b.Zf;this.Ua=null;this.oa="";this.Eb=b.Vf;this.fc={};this.xb=this.Oa=null;this.sc=[];this.V=this.Va=null;this.td=!1;this.fe=0;this.Vb=null;this.Db=-1;this.Kf=()=>this.wf();this.Cb=[];this.B=b.Ae;this.wc="file"===location.protocol.substr(0,4);!this.pa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&oa()||(this.pa=!1);this.pa&&ja&&(this.pa=!1);if("playable-ad"===this.B||"instant-games"===this.B)this.pa=!1;if("cordova"===this.B&&this.pa)if(ia){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.pa=!1)}else this.pa=!1;this.yc=this.Ka=null;"html5"!==this.B||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.K("runtime","cordova-fetch-local-file",c=>this.sf(c));this.K("runtime","create-job-worker",()=>this.tf());"cordova"===this.B?document.addEventListener("deviceready",
()=>this.Vd(b)):this.Vd(b)}j(){this.Yc();this.Ua&&(this.Ua=this.Ua.onmessage=null);this.Oa&&(this.Oa.terminate(),this.Oa=null);this.xb&&(this.xb.j(),this.xb=null);this.V&&(this.V.parentElement.removeChild(this.V),this.V=null)}af(){return ha&&"cordova"===this.B}Tc(){const b=navigator.userAgent;return ha&&za.has(this.B)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(b)}Ze(){return ia}Od(){return ia&&za.has(this.B)}async Vd(b){"macos-wkwebview"===this.B&&this.hd({type:"ready"});if("playable-ad"===
this.B){this.Ka=self.c3_base64files;this.yc={};await this.kf();for(let d=0,e=b.Gb.length;d<e;++d){var c=b.Gb[d];this.yc.hasOwnProperty(c)?b.Gb[d]={Qf:!0,Xf:this.yc[c]}:this.Ka.hasOwnProperty(c)&&(b.Gb[d]=URL.createObjectURL(this.Ka[c]))}b.Mc=[]}if("nwjs"===this.B&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Sd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}b.Uf?this.oa=b.Uf:(c=location.origin,this.oa=("null"===c?"file:///":c)+location.pathname,c=this.oa.lastIndexOf("/"),
-1!==c&&(this.oa=this.oa.substr(0,c+1)));b.ag&&(this.fc=b.ag);c=new MessageChannel;this.Ua=c.port1;this.Ua.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.vf(d));this.Vb=new self.bf(this);await Ba(this.Vb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.pa?await this.rf(b,c.port2):await this.qf(b,c.port2)}$c(b){b=this.fc.hasOwnProperty(b)?this.fc[b]:b.endsWith("/workermain.js")&&this.fc.hasOwnProperty("workermain.js")?this.fc["workermain.js"]:"playable-ad"===this.B&&this.Ka.hasOwnProperty(b)?this.Ka[b]:b;b instanceof Blob&&(b=URL.createObjectURL(b));return b}async Oc(b,c,d){if(b.startsWith("blob:"))return new Worker(b,d);if("cordova"===this.B&&this.wc)return b=await this.hc(d.Pf?b:this.Eb+b),new Worker(URL.createObjectURL(new Blob([b],{type:"application/javascript"})),
d);b=new URL(b,c);if(location.origin!==b.origin){b=await fetch(b);if(!b.ok)throw Error("failed to fetch worker script");b=await b.blob();return new Worker(URL.createObjectURL(b),d)}return new Worker(b,d)}Ha(){return Math.max(window.innerWidth,1)}ya(){return Math.max(window.innerHeight,1)}Ud(b){var c=this.oa,d=location.href,e=this.Ha(),f=this.ya(),g=window.devicePixelRatio,h=a.Lb(),l=b.jg,r=window.cr_previewImageBlobs||this.Ka,v=window.cr_previewProjectFileBlobs,S=window.cr_previewProjectFiles,O=window.gg||
"";b=b.Ae;var E=(new URLSearchParams(self.location.search)).has("debug"),T=this.Vb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:l,previewImageBlobs:r,previewProjectFileBlobs:v,previewProjectFileSWUrls:S,swClientId:O,exportType:b,isDebug:E,ife:!!self.ig,jobScheduler:{inputPort:T.sd,outputPort:T.Ad,maxNumWorkers:T.Gf},supportedAudioFormats:pa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Eb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Eb+"opus.wasm.wasm",isFileProtocol:this.wc,isiOSCordova:this.af(),isiOSWebView:this.Tc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async rf(b,c){const d=this.$c(b.$f);"preview"===this.B?(this.Oa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,l)=>{const r=v=>{this.Oa.removeEventListener("message",r);v.data&&"ok"===v.data.type?h():l()};this.Oa.addEventListener("message",r);this.Oa.postMessage({type:"construct-worker-init","import":(new URL(d,
this.oa)).toString()})})):this.Oa=await this.Oc(d,this.oa,{type:"module",name:"Runtime",Pf:!0});this.V=document.createElement("canvas");this.V.style.display="none";const e=this.V.transferControlToOffscreen();document.body.appendChild(this.V);window.c3canvas=this.V;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=b.Mc||[],g=b.Gb;f=await Promise.all(f.map(h=>this.qb(h)));g=await Promise.all(g.map(h=>this.qb(h)));if("cordova"===this.B)for(let h=0,l=b.Lc.length;h<l;++h){const r=
b.Lc[h],v=r[0];if(v===b.Gd||"scriptsInEvents.js"===v||v.endsWith("/scriptsInEvents.js"))r[1]=await this.qb(v)}this.Oa.postMessage(Object.assign(this.Ud(b),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:b.Lc,mainProjectScript:b.Gd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...Ca(this.Vb)]);this.sc=ua.map(h=>new h(this));this.Td();Da(this.Va);self.c3_callFunction=(h,l)=>{var r=this.Va;return r.u.Qd(r.Pb,"js-invoke-function",
{name:h,params:l},void 0,void 0)};"preview"===this.B&&(self.goToLastErrorScript=()=>this.nb("runtime","go-to-last-error-script"))}async qf(b,c){this.V=document.createElement("canvas");this.V.style.display="none";document.body.appendChild(this.V);window.c3canvas=this.V;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.sc=ua.map(g=>new g(this));this.Td();var d=b.Gb.map(g=>"string"===typeof g?(new URL(g,this.oa)).toString():g);if(Array.isArray(b.Mc)){var e=[...b.Mc].map(g=>g instanceof
Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.qb(g)));await Promise.all(d.map(g=>la(g)));d=self.C3_ProjectScriptsStatus;e=b.Gd;const f=b.Lc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.qb(h),await la(h),"preview"!==this.B||d[g]||this.Xd(g,"main script did not run to completion")}catch(l){this.Xd(g,l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.qb(h),await la(h);"preview"===this.B&&"object"!==typeof self.bg.eg?(this.nc(),
console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(b=Object.assign(this.Ud(b),{isInWorker:!1,messagePort:c,canvas:this.V,runOnStartupFunctions:ya}),Da(this.Va),this.Wd(),this.xb=self.C3_CreateRuntime(b),await self.C3_InitRuntime(this.xb,b))}Xd(b,c){this.nc();console.error(`[Preview] Failed to load project main script (${b}): `,
c);alert(`Failed to load project main script (${b}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Wd(){this.nc()}nc(){const b=window.Mf;b&&(b.parentElement.removeChild(b),window.Mf=null)}async tf(){const b=await Ea(this.Vb);return{outputPort:b,transferables:[b]}}pf(){if(this.pa)throw Error("not available in worker mode");return this.xb}nb(b,c,d,e,f){this.Ua.postMessage({type:"event",component:b,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}Qd(b,c,d,e,f){const g=xa++,h=new Promise((l,r)=>{wa.set(g,{resolve:l,reject:r})});this.Ua.postMessage({type:"event",component:b,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(b){const c=b.type;if("event"===c)return this.uf(b);if("result"===c)this.xf(b);else if("runtime-ready"===c)this.yf();else if("alert-error"===c)this.nc(),alert(b.message);else if("creating-runtime"===c)this.Wd();else throw Error(`unknown message '${c}'`);}uf(b){const c=b.component,d=b.handler,
e=b.data,f=b.responseId;if(b=va.get(c))if(b=b.get(d)){var g=null;try{g=b(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.mc(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.mc(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.mc(f,!1,""+h)}):this.mc(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}mc(b,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.Ua.postMessage({type:"result",responseId:b,isOk:c,result:d},e)}xf(b){const c=b.responseId,d=b.isOk;b=b.result;const e=wa.get(c);d?e.resolve(b):e.reject(b);wa.delete(c)}K(b,c,d){let e=va.get(b);e||(e=new Map,va.set(b,e));if(e.has(c))throw Error(`[DOM] Component '${b}' already has handler '${c}'`);e.set(c,d)}static Hb(b){if(ua.includes(b))throw Error("DOM handler already added");ua.push(b)}Td(){for(const b of this.sc)if("runtime"===b.Pb){this.Va=b;return}throw Error("cannot find runtime DOM handler");
}vf(b){this.nb("debugger","message",b)}yf(){for(const b of this.sc)b.Id()}static Lb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||Aa)}static oc(b){Aa=!!b}Sd(b){this.Cb.push(b);this.gd()}Af(b){b=this.Cb.indexOf(b);if(-1===b)throw Error("invalid callback");this.Cb.splice(b,1);this.Cb.length||this.Yc()}gd(){-1===this.Db&&this.Cb.length&&(this.Db=requestAnimationFrame(this.Kf))}Yc(){-1!==this.Db&&(cancelAnimationFrame(this.Db),this.Db=-1)}wf(){this.Db=
-1;for(const b of this.Cb)b();this.gd()}cb(b){this.Va.cb(b)}ob(b){this.Va.ob(b)}fd(){this.Va.fd()}lc(b){this.Va.lc(b)}$e(){return!!pa["audio/webm; codecs=opus"]}async Bf(b){b=await this.Qd("runtime","opus-decode",{arrayBuffer:b},null,[b]);return new Float32Array(b)}ef(b){this.td=!0;this.fe=b}Ye(b){return/^(?:[a-z\-]+:)?\/\//.test(b)||"data:"===b.substr(0,5)||"blob:"===b.substr(0,5)}Pd(b){return!this.Ye(b)}async qb(b){return"cordova"===this.B&&(b.startsWith("file:")||this.wc&&this.Pd(b))?(b.startsWith(this.oa)&&
(b=b.substr(this.oa.length)),b=await this.hc(b),URL.createObjectURL(new Blob([b],{type:"application/javascript"}))):b}async sf(b){const c=b.filename;switch(b.as){case "text":return await this.We(c);case "buffer":return await this.hc(c);default:throw Error("unsupported type");}}Md(b){const c=window.cordova.file.applicationDirectory+"www/"+b;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async We(b){b=await this.Md(b);return await qa(b)}Zc(){if(sa.length&&!(8<=ta)){ta++;
var b=sa.shift();this.lf(b.filename,b.Yf,b.Of)}}hc(b){return new Promise((c,d)=>{sa.push({filename:b,Yf:e=>{ta--;this.Zc();c(e)},Of:e=>{ta--;this.Zc();d(e)}});this.Zc()})}async lf(b,c,d){try{const e=await this.Md(b),f=await ra(e);c(f)}catch(e){d(e)}}hd(b){if("windows-webview2"===this.B)window.chrome.webview.postMessage(JSON.stringify(b));else if("macos-wkwebview"===this.B)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(b));else throw Error("cannot send wrapper message");}async kf(){const b=
[];for(const [c,d]of Object.entries(this.Ka))b.push(this.jf(c,d));await Promise.all(b)}async jf(b,c){if("object"===typeof c)this.Ka[b]=new Blob([c.str],{type:c.type}),this.yc[b]=c.str;else{let d=await this.nf(c);d||(d=this.mf(c));this.Ka[b]=d}}async nf(b){try{return await (await fetch(b)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}mf(b){b=this.zf(b);return this.hf(b.data,b.Rf)}zf(b){var c=b.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=b.substring(c+1);c=b.substring(5,c).split(";");b=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Rf:b,data:d}}hf(b,c){var d=b.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=b.charCodeAt(l++)|b.charCodeAt(l++)<<8|b.charCodeAt(l++)<<16|b.charCodeAt(l++)<<24;for(d&=
3;d--;)f[l]=b.charCodeAt(l),++l;return new Blob([f],{type:c})}};"use strict";const p=self.Ra;function Fa(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents}const Ga=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),q={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ha={dispatchUserScriptEvent:!0},Ia={dispatchRuntimeEvent:!0};
function Ja(a){return new Promise((b,c)=>{const d=document.createElement("link");d.onload=()=>b(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=a;document.head.appendChild(d)})}function Ka(a){return new Promise((b,c)=>{const d=new Image;d.onload=()=>b(d);d.onerror=e=>c(e);d.src=a})}async function La(a){a=URL.createObjectURL(a);try{return await Ka(a)}finally{URL.revokeObjectURL(a)}}
function Ma(a){return new Promise((b,c)=>{let d=new FileReader;d.onload=e=>b(e.target.result);d.onerror=e=>c(e);d.readAsText(a)})}
async function Na(a,b,c){if(!/firefox/i.test(navigator.userAgent))return await La(a);var d=await Ma(a);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await La(a)}e.setAttribute("width",b+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);a=new Blob([d],{type:"image/svg+xml"});return await La(a)}
function Oa(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;a=a.parentNode}while(a);return!1}const Pa=new Set(["input","textarea","datalist","select"]),Qa=new Set(["canvas","body","html"]);function t(a){a.target.tagName&&Qa.has(a.target.tagName.toLowerCase())&&a.preventDefault()}function Sa(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()}
self.C3_GetSvgImageSize=async function(a){a=await La(a);if(0<a.width&&0<a.height)return[a.width,a.height];a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const b=a.getBoundingClientRect();document.body.removeChild(a);return[b.width,b.height]};self.C3_RasterSvgImageBlob=async function(a,b,c,d,e){a=await Na(a,b,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(a,0,0,b,c);return f};
let Ta=!1;document.addEventListener("pause",()=>Ta=!0);document.addEventListener("resume",()=>Ta=!1);function Da(a){a.ee=!0;a.wd=a.u.Ha();a.Wb=a.u.ya()}async function Ua(a){await Promise.all(a.webfonts.map(async b=>{b=new FontFace(b.name,`url('${b.url}')`);document.fonts.add(b);await b.load()}))}
async function Va(a){var b=a.imageBitmapOpts;a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);b=b?await createImageBitmap(a,b):await createImageBitmap(a);return{imageBitmap:b,transferables:[b]}}async function Wa(a){return await self.C3_GetSvgImageSize(a.blob)}function $a(a){window.c3_postToMessagePort&&(a.from="runtime",window.c3_postToMessagePort(a))}
function ab(a){self.setTimeout(()=>{a.de=!0},1E3);"cordova"===a.u.B?(document.addEventListener("pause",()=>bb(a,!0)),document.addEventListener("resume",()=>bb(a,!1))):document.addEventListener("visibilitychange",()=>bb(a,document.hidden));return{isSuspended:!(!document.hidden&&!Ta)}}
function cb(a){a.Zd||(a.Zd=!0,window.addEventListener("deviceorientation",b=>{a.ma||k(a,"deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},q)}),window.addEventListener("deviceorientationabsolute",b=>{a.ma||k(a,"deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},q)}))}
function db(a){a.Yd||(a.Yd=!0,window.addEventListener("devicemotion",b=>{if(!a.ma){var c=null,d=b.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=b.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=b.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(a,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:b.interval,timeStamp:b.timeStamp},q)}}))}async function eb(a){await Ja(a.url)}
function fb(a,b){a.ge=b.message;-1===a.nd&&(a.nd=setTimeout(()=>{a.nd=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=a.ge)},250))}function gb(a){if(!a.ma){var b=p.Lb();b&&"any"!==a.Dd&&hb(a);k(a,"fullscreenchange",{isFullscreen:b,innerWidth:a.Ha(),innerHeight:a.ya()})}}function ib(a,b){console.warn("[Construct] Fullscreen request failed: ",b);k(a,"fullscreenerror",{isFullscreen:p.Lb(),innerWidth:a.Ha(),innerHeight:a.ya()})}
function bb(a,b){b?a.u.Yc():a.u.gd();k(a,"visibilitychange",{hidden:b})}function jb(a,b,c){"Backspace"===c.key&&t(c);if(!a.ma){var d=Ga.get(c.code)||c.code;aa(a,b,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},q)}}
function kb(a,b,c,d){a.ma||Fa(c)||aa(a,b,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+a.qa,pageX:c.pageX,pageY:c.pageY+a.qa,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function mb(a){window!==window.top&&window.focus();nb(a.target)&&document.activeElement&&!nb(document.activeElement)&&document.activeElement.blur()}
function ob(a,b,c){if(!a.ma){var d=0;"mouse"===c.pointerType&&(d=a.ac);aa(a,b,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+a.qa,pageX:c.pageX,pageY:c.pageY+a.qa,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},q);"mouse"===c.pointerType&&
(d="mousemove","pointerdown"===b?d="mousedown":"pointerup"===b&&(d="mouseup"),kb(a,d,c,Ha),a.ac=c.buttons)}}
function pb(a,b,c){if(!a.ma&&!Fa(c)){var d=a.ac;"pointerdown"===b&&0!==d?b="pointermove":"pointerup"===b&&0!==c.buttons&&(b="pointermove");aa(a,b,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+a.qa,pageX:c.pageX,pageY:c.pageY+a.qa,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},q);a.ac=c.buttons;kb(a,c.type,c,Ha)}}
function qb(a,b,c){if(!a.ma)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];aa(a,b,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+a.qa,pageX:f.pageX,pageY:f.pageY+a.qa,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
q)}}function rb(a,b,c){document.body.style.transform="";a.qa=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),b=(d.top+d.bottom)/2-(b-c)/2,b>c&&(b=c),0>b&&(b=0),0<b&&(document.body.style.transform=`translateY(${-b}px)`,a.qa=b))}}function sb(a,b,c,d){const e=a.Ha(),f=a.ya();a.Fb=-1;e!=b||f!=c?k(a,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:p.Lb()}):10>d&&tb(a,e,f,d+1)}
function tb(a,b,c,d){-1!==a.Fb&&clearTimeout(a.Fb);a.Fb=setTimeout(()=>sb(a,b,c,d),48)}
function hb(a){a=a.Dd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(b=>console.warn("[Construct] Failed to lock orientation: ",b));else try{let b=!1;screen.lockOrientation?b=screen.lockOrientation(a):screen.webkitLockOrientation?b=screen.webkitLockOrientation(a):screen.mozLockOrientation?b=screen.mozLockOrientation(a):screen.msLockOrientation&&(b=screen.msLockOrientation(a));b||console.warn("[Construct] Failed to lock orientation")}catch(b){console.warn("[Construct] Failed to lock orientation: ",
b)}}function nb(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}
p.Hb(class extends self.lb{constructor(a){super(a,"runtime");this.me=!0;this.ee=!1;this.Fb=-1;this.Dd="any";this.Yd=this.Zd=!1;this.Ic=document.createElement("div");this.Ic.className="c3-screen-reader-text";this.Ic.setAttribute("aria-live","polite");document.body.appendChild(this.Ic);this.hb=null;this.ma=!1;this.ge="";this.nd=-1;this.de=!1;this.wd=a.Ha();this.Wb=a.ya();this.qa=this.ec=0;a.K("canvas","update-size",d=>{var e=this.u;e.td||(e=e.V,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.me&&(e.style.display="",this.me=!1))});a.K("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});a.K("runtime","load-webfonts",d=>Ua(d));a.K("runtime","raster-svg-image",d=>Va(d));a.K("runtime","get-svg-image-size",
d=>Wa(d));a.K("runtime","set-target-orientation",d=>{this.Dd=d.targetOrientation});a.K("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});a.K("runtime","post-to-debugger",d=>$a(d));a.K("runtime","go-to-script",d=>$a(d));a.K("runtime","before-start-ticking",()=>ab(this));a.K("runtime","debug-highlight",d=>{if(d.show){this.hb||(this.hb=document.createElement("div"),this.hb.id="inspectOutline",document.body.appendChild(this.hb));var e=this.hb;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.hb&&(this.hb.style.display="none")});a.K("runtime","enable-device-orientation",()=>cb(this));a.K("runtime","enable-device-motion",()=>db(this));a.K("runtime","add-stylesheet",d=>eb(d));a.K("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});a.K("runtime","alert",d=>this.cd(d));a.K("runtime",
"screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.Ic.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
a.K("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});a.K("runtime","set-exporting-to-video",d=>{this.ma=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.u.V.style.display="";this.u.ef(d.duration)});a.K("runtime","export-to-video-progress",d=>fb(this,d));a.K("runtime","exported-to-video",d=>{window.Lf({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});a.K("runtime","exported-to-image-sequence",d=>{window.Lf({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const b=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;b.has(e.tagName.toLowerCase())||Oa(e)||d.preventDefault()});const c=a.V;window.addEventListener("selectstart",t);window.addEventListener("gesturehold",t);c.addEventListener("selectstart",t);c.addEventListener("gesturehold",
t);window.addEventListener("touchstart",t,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",t,{passive:!1}),c.addEventListener("pointerdown",t)):c.addEventListener("touchstart",t);this.ac=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Sa,{passive:!1});window.addEventListener("wheel",Sa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ma&&this.ee){var d=this.Ha();var e=this.ya();if(this.u.Od()){if(this.de){if(this.wd===
d&&e<this.Wb){this.ec=this.Wb-e;rb(this,this.Wb,this.ec);d=void 0;break a}0<this.ec&&(this.ec=0,rb(this,e,this.ec))}this.wd=d;this.Wb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:p.Lb()});this.u.Tc()&&(-1!==this.Fb&&clearTimeout(this.Fb),sb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>gb(this));window.addEventListener("webkitfullscreenchange",()=>gb(this));window.addEventListener("mozfullscreenchange",
()=>gb(this));window.addEventListener("fullscreenerror",d=>ib(this,d));window.addEventListener("webkitfullscreenerror",d=>ib(this,d));window.addEventListener("mozfullscreenerror",d=>ib(this,d));if(a.Tc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=
new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Oa(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(p.oc(!0),gb(this)):"exited-fullscreen"===d?(p.oc(!1),gb(this)):console.warn("Unknown wrapper message: ",d)};this.yb=new Set;this.Ac=new WeakSet;this.Ta=!1}Id(){window.addEventListener("focus",()=>{k(this,"window-focus",null,Ia)});window.addEventListener("blur",
()=>{try{var b=window.parent&&window.parent.document.hasFocus()}catch(c){b=!1}k(this,"window-blur",{parentHasFocus:b},Ia);this.ac=0});window.addEventListener("focusin",b=>{b=b.target;(Pa.has(b.tagName.toLowerCase())||Oa(b))&&k(this,"keyboard-blur",null,Ia)});window.addEventListener("keydown",b=>jb(this,"keydown",b));window.addEventListener("keyup",b=>jb(this,"keyup",b));window.addEventListener("dblclick",b=>kb(this,"dblclick",b,q));window.addEventListener("wheel",b=>{this.ma||k(this,"wheel",{clientX:b.clientX,
clientY:b.clientY+this.qa,pageX:b.pageX,pageY:b.pageY+this.qa,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},q)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",b=>{mb(b);ob(this,"pointerdown",b)}),this.u.pa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",b=>{ob(this,"pointermove",b)}):window.addEventListener("pointermove",b=>ob(this,"pointermove",b)),window.addEventListener("pointerup",
b=>ob(this,"pointerup",b)),window.addEventListener("pointercancel",b=>ob(this,"pointercancel",b))):(window.addEventListener("mousedown",b=>{mb(b);pb(this,"pointerdown",b)}),window.addEventListener("mousemove",b=>pb(this,"pointermove",b)),window.addEventListener("mouseup",b=>pb(this,"pointerup",b)),window.addEventListener("touchstart",b=>{mb(b);qb(this,"pointerdown",b)}),window.addEventListener("touchmove",b=>qb(this,"pointermove",b)),window.addEventListener("touchend",b=>qb(this,"pointerup",b)),window.addEventListener("touchcancel",
b=>qb(this,"pointercancel",b)));const a=()=>this.fd();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);window.addEventListener("keydown",a,!0);window.addEventListener("gamepadconnected",a,!0);this.u.Ze()&&!this.u.Od()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{rb(this,this.ya(),navigator.virtualKeyboard.boundingRect.height)}))}Ha(){return this.u.Ha()}ya(){return this.u.ya()}fd(){var a=
[...this.yb];this.yb.clear();if(!this.Ta)for(const b of a)(a=b.play())&&a.catch(()=>{this.Ac.has(b)||this.yb.add(b)})}cb(a){if("function"!==typeof a.play)throw Error("missing play function");this.Ac.delete(a);let b;try{b=a.play()}catch(c){this.yb.add(a);return}b&&b.catch(()=>{this.Ac.has(a)||this.yb.add(a)})}ob(a){this.yb.delete(a);this.Ac.add(a)}lc(a){this.Ta=!!a}cd(a){alert(a.message)}});"use strict";
async function Ba(a){if(a.Cf)throw Error("already initialised");a.Cf=!0;var b=a.Wa.$c(("playable-ad"===a.Wa.B?a.Wa.Eb:"")+"dispatchworker.js");a.md=await a.Wa.Oc(b,a.Ob,{name:"DispatchWorker"});b=new MessageChannel;a.sd=b.port1;a.md.postMessage({type:"_init","in-port":b.port2},[b.port2]);a.Ad=await Ea(a)}function Ca(a){return[a.sd,a.Ad]}
async function Ea(a){const b=a.ne.length;var c=a.Wa.$c(("playable-ad"===a.Wa.B?a.Wa.Eb:"")+"jobworker.js");c=await a.Wa.Oc(c,a.Ob,{name:"JobWorker"+b});const d=new MessageChannel,e=new MessageChannel;a.md.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:b,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);a.ne.push(c);return e.port1}
self.bf=class{constructor(a){this.Wa=a;this.Ob=a.oa;this.Ob="preview"===a.B?this.Ob+"workers/":this.Ob+a.Eb;this.Gf=Math.min(navigator.hardwareConcurrency||2,16);this.md=null;this.ne=[];this.Ad=this.sd=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ra({Zf:!0,$f:"workermain.js",Gb:["scripts/c3runtime.js"],Lc:[],Gd:"",Vf:"scripts/",Mc:[],Ae:"html5"}));"use strict";
async function ub(a,b){b=b.type;let c=!0;0===b?c=await vb():1===b&&(c=await wb());k(a,"permission-result",{type:b,result:c})}async function vb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(a){return console.warn("[Touch] Failed to request orientation permission: ",a),!1}}
async function wb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(a){return console.warn("[Touch] Failed to request motion permission: ",a),!1}}self.Ra.Hb(class extends self.lb{constructor(a){super(a,"touch");ba(this,"request-permission",b=>ub(this,b))}});"use strict";function xb(){}
function yb(a){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(b=>k(a,"sw-message",b.data))}
function zb(a){a=a.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(b=>console.warn("[Construct] Failed to lock orientation: ",b));else try{let b=!1;screen.lockOrientation?b=screen.lockOrientation(a):screen.webkitLockOrientation?b=screen.webkitLockOrientation(a):screen.mozLockOrientation?b=screen.mozLockOrientation(a):screen.msLockOrientation&&(b=screen.msLockOrientation(a));b||console.warn("[Construct] Failed to lock orientation")}catch(b){console.warn("[Construct] Failed to lock orientation: ",
b)}}
self.Ra.Hb(class extends self.lb{constructor(a){super(a,"browser");this.B="";ca(this,[["get-initial-state",b=>{this.B=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
yb(this)],["alert",b=>this.cd(b)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",b=>this.ed(b)],["vibrate",b=>{navigator.vibrate&&navigator.vibrate(b.pattern)}],["lock-orientation",b=>zb(b)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(b){}}],["navigate",b=>{var c=b.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=b.url;const d=b.target;b=b.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===b||"windows-webview2"===b?window.open(c,"_blank"):this.fg||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=b.url,b=b.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,b))}],["request-fullscreen",b=>{if("windows-webview2"===this.B||"macos-wkwebview"===this.B)self.Ra.oc(!0),this.u.hd({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};b=b.navUI;1===
b?c.navigationUI="hide":2===b&&(c.navigationUI="show");b=document.documentElement;let d;b.requestFullscreen?d=b.requestFullscreen(c):b.mozRequestFullScreen?d=b.mozRequestFullScreen(c):b.msRequestFullscreen?d=b.msRequestFullscreen(c):b.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?b.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):b.webkitRequestFullScreen());d instanceof Promise&&d.catch(xb)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.B||"macos-wkwebview"===
this.B)self.Ra.oc(!1),this.u.hd({type:"set-fullscreen",fullscreen:!1});else{let b;document.exitFullscreen?b=document.exitFullscreen():document.mozCancelFullScreen?b=document.mozCancelFullScreen():document.msExitFullscreen?b=document.msExitFullscreen():document.webkitCancelFullScreen&&(b=document.webkitCancelFullScreen());b instanceof Promise&&b.catch(xb)}}],["set-hash",b=>{location.hash=b.hash}],["set-document-css-style",b=>{const c=b.prop,d=b.value;var e=b.selector;b=b["is-all"];try{if(e)if(b)var f=
Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",b=>{{const d=b.prop;b=b.selector;try{const e=document.querySelector(b);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),
c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}cd(a){alert(a.message)}ed(a){a=a.isFocus;if("nwjs"===this.B){const b="nwjs"===this.B?nw.Window.get():null;a?b.focus():b.blur()}else a?window.focus():window.blur()}});
"use strict";const Ab=180/Math.PI;
async function Bb(a,b){if(b.isiOSCordova||b.isSafari)a.Dc=!0;a.Ed=b.timeScaleMode;a.se=["equalpower","HRTF","soundfield"][b.panningModel];a.be=["linear","inverse","exponential"][b.distanceModel];a.te=b.refDistance;a.re=b.maxDistance;a.ve=b.rolloffFactor;if(a.u.td)a.Dc=!0,a.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*a.u.fe)});else{var c={latencyHint:b.latencyHint};a.ye||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)a.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)a.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");Cb(a);a.g.onstatechange=()=>{"running"!==a.g.state&&Cb(a);k(a,"audiocontext-state",{audioContextState:a.g.state})}}a.tb=a.g.createGain();a.tb.connect(a.g.destination);c=b.listenerPos;a.na[0]=c[0];a.na[1]=c[1];a.na[2]=c[2];a.g.listener.setPosition(c[0],c[1],c[2]);a.g.listener.setOrientation(...a.ua);self.C3_GetAudioContextCurrentTime=()=>a.g.currentTime;try{await Promise.all(b.preloadList.map(d=>
Db(a,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:a.g.sampleRate,audioContextState:a.g.state,outputLatency:a.g.outputLatency||0}}
async function Eb(a,b){var c=b.originalUrl,d=b.url;const e=b.type,f=b.isMusic,g=b.tags,h=b.isLooping,l=b.vol,r=b.pos,v=b.panning,S=b.stereoPan;let O=b.off;0<O&&!b.trueClock&&(a.g.getOutputTimestamp?(b=a.g.getOutputTimestamp(),O=O-b.performanceTime/1E3+b.contextTime):O=O-performance.now()/1E3+a.g.currentTime);a.oe=g.slice(0);Fb(a,g);try{a.ca=await Gb(a,c,d,e,g,f);if(v){Hb(a.ca,!0);var E=a.ca,T=v.innerAngle,Xa=v.outerAngle,Za=v.outerGain;if(E.Ub){Jb(E,v.x,v.y,v.z,v.angle);var W=self.Ib.gf;E.La[0]!==
W(T)&&(E.La[0]=W(T),E.M.coneInnerAngle=W(T));E.La[1]!==W(Xa)&&(E.La[1]=W(Xa),E.M.coneOuterAngle=W(Xa));E.La[2]!==Za&&(E.La[2]=Za,E.M.coneOuterGain=Za)}v.hasOwnProperty("uid")&&(a.ca.Ja=v.uid)}else"number"===typeof S&&0!==S?(u(a.ca,!0),Kb(a.ca,S)):(Hb(a.ca,!1),u(a.ca,!1));a.ca.Play(h,l,r,O)}catch(ad){console.error("[Construct] Audio: error starting playback: ",ad);return}finally{c=g.join(" ");d=a.cc.get(c);if(!d)throw Error("expected pending tag");d.Hd--;0===d.Hd&&(d.resolve(),a.cc.delete(c))}da(a)}
async function Lb(a,b){var c=b.tags;const d=b.vol,e=b.duration;b=b.stopOnEnd;await Mb(a,c);for(const v of w(a,c)){c=v;var f=d,g=e,h=b;if(!c.vb){var l=c.N.gain;l.cancelScheduledValues(0);var r=c.A.g.currentTime;g=r+g;l.setValueAtTime(l.value,r);l.linearRampToValueAtTime(f,g);c.kb=f;c.ub=g;c.xe=h}}Nb(a)}async function Ob(a,b){const c=b.tags;b=b.rate;await Mb(a,c);for(const d of w(a,c))a=d,a.Ca!==b&&(a.Ca=b,a.eb())}
async function Pb(a,b){const c=b.tags;b=b.pos;await Mb(a,c);for(const d of w(a,c))d.Uc(b)}async function Qb(a,b){const c=b.originalUrl,d=b.url,e=b.type;b=b.isMusic;try{await Gb(a,c,d,e,"",b)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Rb(a,b){if(b=await Db(a,"",b.url,b.type,b.isMusic,!0))b.j(),b=a.Aa.indexOf(b),-1!==b&&a.Aa.splice(b,1)}
async function Sb(a,b){const c=b.type;var d=b.tags;const e=b.params;let f;if("convolution"===c)try{f=await Db(a,b.bufferOriginalUrl,b.bufferUrl,b.bufferType,!1)}catch(l){console.log("[Construct] Audio: error loading convolution: ",l);return}for(const l of d){if("filter"===c)d=new self.Ge(a,...e);else if("delay"===c)d=new self.Ee(a,...e);else if("convolution"===c){var g=d=new self.De(a,f.za,...e),h=b.bufferType;g.$d=b.bufferOriginalUrl;g.ae=h}else if("flanger"===c)d=new self.He(a,...e);else if("phaser"===
c)d=new self.Je(a,...e);else if("gain"===c)d=new self.Ie(a,...e);else if("stereopan"===c)d=new self.Le(a,...e);else if("tremolo"===c)d=new self.Me(a,...e);else if("ringmod"===c)d=new self.Ke(a,...e);else if("distortion"===c)d=new self.Fe(a,...e);else if("compressor"===c)d=new self.Ce(a,...e);else if("analyser"===c)d=new self.Be(a,...e);else throw Error("invalid effect type");g=a;h=l;h=h.toLowerCase();let r=g.Ba.get(h);r||(r=[],g.Ba.set(h,r));d.le=r.length;d.Cd=h;r.push(d);Tb(g,h)}Ub(a)}
async function Vb(a,b){const c=b.saveLoadMode;if(3!==c){var d=[];for(var e of a.P)e.$a()&&1===c||!e.$a()&&2===c?d.push(e):e.j();a.P=d}for(const f of a.Ba.values())for(const g of f)g.j();a.Ba.clear();a.Jc=b.timeScale;a.od=b.gameTime;d=b.listenerPos;a.na[0]=d[0];a.na[1]=d[1];a.na[2]=d[2];a.g.listener.setPosition(d[0],d[1],d[2]);d=b.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)a.ua[e]=d[e];a.g.listener.setOrientation(...a.ua)}a.Ta=b.isSilent;a.u.lc(a.Ta);a.zc=b.masterVolume;a.tb.gain.value=
a.zc;d=[];for(const f of Object.values(b.effects))d.push(Promise.all(f.map(g=>Sb(a,g))));await Promise.all(d);await Promise.all(b.playing.map(f=>Wb(a,f,c)));Nb(a)}
async function Xb(a,b){try{const c=a.g.suspend(b.time);a.ke?a.g.resume():(a.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}a.u.nb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Yb(d)),a.ke=!0);await c}catch(c){Yb(c)}}
function Cb(a){a.uc||(a.rd=!1,window.addEventListener("pointerup",a.Xa,!0),window.addEventListener("touchend",a.Xa,!0),window.addEventListener("click",a.Xa,!0),window.addEventListener("keydown",a.Xa,!0),a.uc=!0)}
async function Db(a,b,c,d,e,f){for(var g of a.Aa)if(g.Kb()===c)return await g.U(),g;if(f)return null;if(e&&(a.Dc||a.je)){f=0;for(let h=0,l=a.Aa.length;h<l;++h)g=a.Aa[h],a.Aa[f]=g,g.$a()?g.j():++f;a.Aa.length=f}f="audio/webm; codecs=opus"===d&&!a.ye;e&&f&&(a.je=!0);c=!e||a.Dc||f?new self.Ue(a,b,c,d,e,f):new self.Pe(a,b,c,d,e);a.Aa.push(c);await c.U();a.qe.has(b)||(k(a,"buffer-metadata",{originalUrl:b,duration:c.xa()}),a.qe.add(b));return c}
function Zb(a,b){return a===b||a.normalize().toLowerCase()===b.normalize().toLowerCase()}function $b(a,b){return(b=a.Ba.get(b.toLowerCase()))?b[0].Z():a.Ga()}function Tb(a,b){b=b.toLowerCase();let c=a.Ga();var d=a.Ba.get(b);if(d&&d.length){c=d[0].Z();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.fa(a.Ga()):e.fa(d[f+1].Z())}}for(const f of ac(a,b))d=c,e=f.wa||f.M||f.N,e.disconnect(),e.connect(d);a.ib&&a.yd===b&&(a.ib.disconnect(),a.ib.connect(c))}
function*ac(a,b){if(b)for(const c of a.P)Zb(0<c.Da.length?c.Da[0]:"",b)&&(yield c);else a.ca&&!a.ca.$()&&(yield a.ca)}function bc(a,b,c){return c?a.u.Bf(b).then(d=>{const e=a.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{a.g.decodeAudioData(b,d,e)})}function cc(a,b){let c=0;for(let d=0,e=a.P.length;d<e;++d){const f=a.P[d];a.P[c]=f;f.ba===b?f.j():++c}a.P.length=c}
function*w(a,b){if(0<b.length)for(const d of a.P){a:{a=d.Da;var c=b;for(const e of c){c=!1;for(const f of a)if(Zb(f,e)){c=!0;break}if(!c){a=!1;break a}}a=!0}a&&(yield d)}else a.ca&&!a.ca.$()&&(yield a.ca)}async function Gb(a,b,c,d,e,f){for(const g of a.P)if(g.Kb()===c&&(g.Nc()||f))return g.Da=e,g;b=await Db(a,b,c,d,f);e="html5"===b.jd?new self.Qe(b.A,b,e):new self.Ve(b.A,b,e);a.P.push(e);return e}
function Fb(a,b){b=b.join(" ");let c=a.cc.get(b);if(!c){let d=null;c={Hd:0,promise:new Promise(e=>d=e),resolve:d};a.cc.set(b,c)}c.Hd++}function Mb(a,b){return(a=a.cc.get((0===b.length?a.oe:b).join(" ")))?a.promise:Promise.resolve()}function Nb(a){if(0<a.rb.size)da(a);else for(const b of a.P)if(!b.R&&!b.$()){da(a);break}}function dc(a,b,c,d){k(a,"trigger",{type:b,tags:c,aiid:d})}function Ub(a){a.ud||(a.ud=!0,Promise.resolve().then(()=>ec(a)))}
function ec(a){const b={};for(const [c,d]of a.Ba)b[c]=d.map(e=>e.Jb());k(a,"fxstate",{fxstate:b});a.ud=!1}
async function Wb(a,b,c){if(3!==c){var d=b.bufferOriginalUrl,e=b.bufferUrl,f=b.bufferType,g=b.isMusic,h=b.tags,l=b.isLooping,r=b.volume,v=b.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await Gb(a,d,e,f,h,g)}catch(S){console.error("[Construct] Audio: error loading audio state: ",S);return}a=c;(d=b.pan)?(Hb(a,!0),e=a.M,f=d.pos,a.Ab[0]=f[0],a.Ab[1]=f[1],a.Ab[2]=f[2],f=d.orient,a.zb[0]=f[0],a.zb[1]=f[1],a.zb[2]=f[2],e.setPosition(...a.Ab),e.setOrientation(...a.zb),a.La[0]=d.cia,a.La[1]=d.coa,a.La[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,a.Ja=d.uid):Hb(a,!1);a=c;d=b.stereoPan;"number"!==typeof d?u(a,!1):(u(a,!0),Kb(a,d));c.Play(l,r,v,0);b.isPlaying||c.Mb();c.bd(b)}}}function Yb(a){console.error("[Audio] Offline rendering error: ",a)}
self.Ib=class extends self.lb{constructor(a){super(a,"audio");this.tb=this.g=null;this.uc=this.rd=!1;this.Xa=()=>{if(!this.rd){var b=this.g;"suspended"===b.state&&b.resume&&b.resume();var c=b.createBuffer(1,220,22050),d=b.createBufferSource();d.buffer=c;d.connect(b.destination);d.start(0);"running"===b.state&&this.uc&&(this.rd=!0,window.removeEventListener("pointerup",this.Xa,!0),window.removeEventListener("touchend",this.Xa,!0),window.removeEventListener("click",this.Xa,!0),window.removeEventListener("keydown",
this.Xa,!0),this.uc=!1)}};this.Aa=[];this.P=[];this.ca=null;this.oe=[];this.qe=new Set;this.pe=-1;this.cc=new Map;this.zc=1;this.Ta=!1;this.Ed=0;this.Jc=1;this.od=0;this.se="HRTF";this.be="inverse";this.te=600;this.re=1E4;this.ve=1;this.na=[0,0,0];this.ua=[0,0,-1,0,1,0];this.je=this.Dc=!1;this.ye=this.u.$e();this.Ba=new Map;this.rb=new Set;this.ke=this.ud=!1;this.yd="";this.ib=null;self.C3Audio_OnMicrophoneStream=(b,c)=>{this.ib&&this.ib.disconnect();this.yd=c.toLowerCase();this.ib=this.g.createMediaStreamSource(b);
this.ib.connect($b(this,this.yd))};this.rc=null;self.C3Audio_GetOutputStream=()=>{this.rc||(this.rc=this.g.createMediaStreamDestination(),this.tb.connect(this.rc));return this.rc.stream};self.C3Audio_DOMInterface=this;ca(this,[["create-audio-context",b=>Bb(this,b)],["play",b=>Eb(this,b)],["stop",b=>{b=b.tags;for(const c of w(this,b))c.bb()}],["stop-all",()=>{for(const b of this.P)b.bb()}],["set-paused",b=>{const c=b.tags;b=b.paused;for(const d of w(this,c))b?d.Mb():d.kc();Nb(this)}],["set-volume",
b=>{const c=b.tags;b=b.vol;for(const d of w(this,c))x(d,b)}],["fade-volume",b=>Lb(this,b)],["set-master-volume",b=>{this.zc=b.vol;this.tb.gain.value=this.zc}],["set-muted",b=>{const c=b.tags;b=b.isMuted;for(const d of w(this,c))fc(d,b)}],["set-silent",b=>{this.Ta=b.isSilent;this.u.lc(this.Ta);for(const c of this.P)c.pc()}],["set-looping",b=>{const c=b.tags;b=b.isLooping;for(const d of w(this,c))d.Vc(b)}],["set-playback-rate",b=>Ob(this,b)],["set-stereo-pan",b=>{const c=b.tags;b=b.p;for(const d of w(this,
c))u(d,!0),Kb(d,b)}],["seek",b=>Pb(this,b)],["preload",b=>Qb(this,b)],["unload",b=>Rb(this,b)],["unload-all",()=>{for(const b of this.Aa)b.j();this.Aa.length=0}],["set-suspended",b=>{b=b.isSuspended;!b&&this.g.resume&&this.g.resume();for(const c of this.P)c.Wc(b);b&&this.g.suspend&&this.g.suspend()}],["add-effect",b=>Sb(this,b)],["set-effect-param",b=>{var c=b.tags;const d=b.index,e=b.param,f=b.value,g=b.ramp;b=b.time;for(const h of c)c=this.Ba.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].la(e,
f,g,b);Ub(this)}],["remove-effects",b=>{b=b.tags;for(const c of b){b=c.toLowerCase();const d=this.Ba.get(b);if(!d||!d.length)break;for(const e of d)e.j();this.Ba.delete(b);Tb(this,b)}}],["tick",b=>{this.Jc=b.timeScale;this.od=b.gameTime;this.pe=b.tickCount;if(0!==this.Ed)for(var c of this.P)c.eb();!(c=b.listenerPos)||this.na[0]===c[0]&&this.na[1]===c[1]&&this.na[2]===c[2]||(this.na[0]=c[0],this.na[1]=c[1],this.na[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=b.listenerOrientation)&&(this.ua[0]!==
c[0]||this.ua[1]!==c[1]||this.ua[2]!==c[2]||this.ua[3]!==c[3]||this.ua[4]!==c[4]||this.ua[5]!==c[5])){for(let d=0;6>d;++d)this.ua[d]=c[d];this.g.listener.setOrientation(...this.ua)}for(const d of b.instPans){b=d.uid;for(const e of this.P)e.Ja===b&&Jb(e,d.x,d.y,d.z,d.angle)}}],["load-state",b=>Vb(this,b)],["offline-render-audio",b=>Xb(this,b)],["offline-render-finish",()=>{this.g.resume()}]])}ia(){return this.g}Ga(){return this.tb}jc(){return this.Ta}cb(a){this.u.cb(a)}ob(a){this.u.ob(a)}pb(){for(var a of this.rb)a.pb();
a=this.g.currentTime;for(var b of this.P)b.pb(a);b=this.P.filter(c=>!c.R&&!c.$()).map(c=>c.Jb());k(this,"state",{tickCount:this.pe,outputLatency:this.g.outputLatency||0,audioInstances:b,analysers:[...this.rb].map(c=>({tag:c.Cd,index:c.le,peak:c.Bb,rms:c.ue,binCount:c.l.frequencyBinCount,freqBins:c.he}))});0===b.length&&0===this.rb.size&&this.vc&&(this.u.Af(this.ze),this.vc=!1)}static gf(a){return a*Ab}static Nd(a){return Math.max(Math.min(Math.pow(10,a/20),1),0)}static cf(a){return Math.log(Math.max(Math.min(a,
1),0))/Math.log(10)*20}};self.Ra.Hb(self.Ib);"use strict";self.Kd=class{constructor(a,b,c,d,e){this.A=a;this.If=b;this.jb=c;this.ea=d;this.Ef=e;this.jd="";this.m=null}j(){this.m=this.A=null}ad(){}U(){this.m||(this.m=this.ad());return this.m}ia(){return this.A.ia()}Qc(){return this.If}Kb(){return this.jb}Pc(){return this.ea}$a(){return this.Ef}xa(){}};"use strict";
self.Pe=class extends self.Kd{constructor(a,b,c,d,e){super(a,b,c,d,e);this.jd="html5";this.Y=new Audio;this.Y.crossOrigin="anonymous";this.Y.autoplay=!1;this.Y.preload="auto";this.Xb=this.Yb=null;this.Y.addEventListener("canplaythrough",()=>!0);this.bc=this.ia().createGain();this.$b=null;this.Y.addEventListener("canplay",()=>{this.Yb&&(this.Yb(),this.Xb=this.Yb=null);!this.$b&&this.Y&&(this.$b=this.ia().createMediaElementSource(this.Y),this.$b.connect(this.bc))});this.onended=null;this.Y.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.Y.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.jb}' error: `,f);this.Xb&&(this.Xb(f),this.Xb=this.Yb=null)})}j(){cc(this.A,this);this.bc.disconnect();this.bc=null;this.$b.disconnect();this.$b=null;this.Y&&!this.Y.paused&&this.Y.pause();this.Y=this.onended=null;super.j()}ad(){return new Promise((a,b)=>{this.Yb=a;this.Xb=b;this.Y.src=this.jb})}ga(){return this.Y}xa(){return this.Y.duration}};"use strict";
async function gc(a){if(a.gb)return a.gb;var b=a.A.u;if("cordova"===b.B&&b.Pd(a.jb)&&b.wc)a.gb=await b.hc(a.jb);else{b=await fetch(a.jb);if(!b.ok)throw Error(`error fetching audio data: ${b.status} ${b.statusText}`);a.gb=await b.arrayBuffer()}}async function hc(a){if(a.za)return a.za;a.za=await bc(a.A,a.gb,a.Hf);a.gb=null}
self.Ue=class extends self.Kd{constructor(a,b,c,d,e,f){super(a,b,c,d,e);this.jd="webaudio";this.za=this.gb=null;this.Hf=!!f}j(){cc(this.A,this);this.za=this.gb=null;super.j()}async ad(){try{await gc(this),await hc(this)}catch(a){console.error(`[Construct] Failed to load audio '${this.jb}': `,a)}}xa(){return this.za?this.za.duration:0}};"use strict";let ic=0;
function Hb(a,b){b=!!b;a.Ub!==b&&(a.Ub=b,a.Ub?(u(a,!1),a.M||(a.M=a.ia().createPanner(),a.M.panningModel=a.A.se,a.M.distanceModel=a.A.be,a.M.refDistance=a.A.te,a.M.maxDistance=a.A.re,a.M.rolloffFactor=a.A.ve),a.N.disconnect(),a.N.connect(a.M),a.M.connect(a.Ga())):(a.M.disconnect(),a.N.disconnect(),a.N.connect(a.Ga())))}
function u(a,b){b=!!b;a.xc!==b&&(a.xc=b,a.xc?(Hb(a,!1),a.wa=a.ia().createStereoPanner(),a.N.disconnect(),a.N.connect(a.wa),a.wa.connect(a.Ga())):(a.wa.disconnect(),a.wa=null,a.N.disconnect(),a.N.connect(a.Ga())))}function Kb(a,b){a.xc&&a.Bd!==b&&(a.wa.pan.value=b,a.Bd=b)}function x(a,b){a.kb=b;a.N.gain.cancelScheduledValues(0);a.ub=-1;a.N.gain.value=a.Rc()}function fc(a,b){b=!!b;a.vb!==b&&(a.vb=b,a.pc())}
function Jb(a,b,c,d,e){if(a.Ub){var f=a.Ab,g=a.zb,h=Math.cos(e);e=Math.sin(e);if(f[0]!==b||f[1]!==c||f[2]!==d)f[0]=b,f[1]=c,f[2]=d,a.M.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,a.M.setOrientation(...g)}}function jc(a){return a.vd?a.A.od:performance.now()/1E3}
self.Ld=class{constructor(a,b,c){this.A=a;this.ba=b;this.Da=c;this.qc=ic++;this.N=this.ia().createGain();this.N.connect(this.Ga());this.M=null;this.Ub=!1;this.Ab=[0,0,0];this.zb=[0,0,0];this.La=[0,0,0];this.wa=null;this.xc=!1;this.Bd=0;this.R=!0;this.ka=this.Ma=this.W=!1;this.kb=1;this.vb=!1;this.Ca=1;a=this.A.Ed;this.vd=1===a&&!this.$a()||2===a;this.ub=this.Ja=-1;this.xe=!1}j(){this.ba=this.A=null;this.M&&(this.M.disconnect(),this.M=null);this.wa&&(this.wa.disconnect(),this.wa=null);this.N.disconnect();
this.N=null}ia(){return this.A.ia()}Ga(){return $b(this.A,0<this.Da.length?this.Da[0]:"")}Qc(){return this.ba.Qc()}Kb(){return this.ba.Kb()}Pc(){return this.ba.Pc()}$a(){return this.ba.$a()}$(){}Nc(){}IsPlaying(){return!this.R&&!this.W&&!this.$()}mb(){}xa(){return this.ba.xa()}Play(){}bb(){}Mb(){}kc(){}pb(a){-1!==this.ub&&a>=this.ub&&(this.ub=-1,this.xe&&this.bb(),dc(this.A,"fade-ended",this.Da,this.qc))}Rc(){const a=this.kb;return isFinite(a)?a:0}jc(){return this.A.jc()}pc(){}Vc(){}eb(){}Uc(){}Wc(){}Sc(){}Jb(){var a=
this.qc,b=this.Da,c=this.xa(),d=-1===this.ub?this.kb:this.N.gain.value,e=this.IsPlaying();if(this.M){var f=this.M;f={pos:this.Ab,orient:this.zb,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.Ja}}else f=null;return{aiid:a,tags:b,duration:c,volume:d,isPlaying:e,playbackTime:this.mb(),playbackRate:this.Ca,uid:this.Ja,bufferOriginalUrl:this.Qc(),bufferUrl:"",bufferType:this.Pc(),isMusic:this.$a(),isLooping:this.ka,isMuted:this.vb,resumePosition:this.Sc(),pan:f,stereoPan:this.wa?
this.Bd:null}}bd(a){var b=a.playbackRate;this.Ca!==b&&(this.Ca=b,this.eb());fc(this,a.isMuted)}};"use strict";
self.Qe=class extends self.Ld{constructor(a,b,c){super(a,b,c);this.ba.bc.connect(this.N);this.ba.onended=()=>this.dd()}j(){this.bb();this.ba.bc.disconnect();super.j()}ga(){return this.ba.ga()}dd(){this.R=!0;this.Ja=-1;dc(this.A,"ended",this.Da,this.qc)}$(){return this.ga().ended}Nc(){return this.R?!0:this.$()}mb(){let a=this.ga().currentTime;this.ka||(a=Math.min(a,this.xa()));return a}Play(a,b,c){const d=this.ga();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==a&&(d.loop=a);x(this,b);d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.ba.Kb()}' to position '${c}': `,e)}this.A.cb(d);this.W=this.R=!1;this.ka=a;this.Ca=1}bb(){const a=this.ga();a.paused||a.pause();this.A.ob(a);this.R=!0;this.W=!1;this.Ja=-1}Mb(){if(!(this.W||this.R||this.$())){var a=this.ga();a.paused||a.pause();this.A.ob(a);this.W=!0}}kc(){!this.W||this.R||this.$()||(this.A.cb(this.ga()),this.W=!1)}pc(){this.ga().muted=this.vb||this.jc()}Vc(a){a=!!a;this.ka!==
a&&(this.ka=a,this.ga().loop=a)}eb(){let a=this.Ca;this.vd&&(a*=this.A.Jc);try{this.ga().playbackRate=a}catch(b){console.warn(`[Construct] Unable to set playback rate '${a}':`,b)}}Uc(a){if(!this.R&&!this.$())try{this.ga().currentTime=a}catch(b){console.warn(`[Construct] Error seeking audio to '${a}': `,b)}}Sc(){return this.mb()}Wc(a){a?this.IsPlaying()?(this.ga().pause(),this.Ma=!0):this.Ma=!1:this.Ma&&(this.A.cb(this.ga()),this.Ma=!1)}};"use strict";
function kc(a){a.s&&(a.s.onended=null,a.s.disconnect(),a.s.buffer=null);a.s=null;a.Nb=null}
self.Ve=class extends self.Ld{constructor(a,b,c){super(a,b,c);this.s=null;this.Bc=d=>this.dd(d);this.qd=!0;this.Nb=null;this.da=this.Cc=this.Ec=0;this.zd=1}j(){this.bb();kc(this);this.Bc=null;super.j()}dd(a){this.W||this.Ma||a.target!==this.Nb||(this.R=this.qd=!0,this.Ja=-1,kc(this),dc(this.A,"ended",this.Da,this.qc))}$(){return!this.R&&this.s&&this.s.loop||this.W?!1:this.qd}Nc(){return!this.s||this.R?!0:this.$()}mb(){let a;a=this.W?this.da:this.Cc+(jc(this)-this.Ec)*this.Ca;this.ka||(a=Math.min(a,
this.xa()));return a}Play(a,b,c,d){this.zd=1;x(this,b);kc(this);this.s=this.ia().createBufferSource();this.s.buffer=this.ba.za;this.s.connect(this.N);this.Nb=this.s;this.s.onended=this.Bc;this.s.loop=a;this.s.start(d,c);this.W=this.R=this.qd=!1;this.ka=a;this.Ca=1;this.Ec=jc(this);this.Cc=c}bb(){if(this.s)try{this.s.stop(0)}catch(a){}this.R=!0;this.W=!1;this.Ja=-1}Mb(){this.W||this.R||this.$()||(this.da=this.mb(),this.ka&&(this.da%=this.xa()),this.W=!0,this.s.stop(0))}kc(){!this.W||this.R||this.$()||
(kc(this),this.s=this.ia().createBufferSource(),this.s.buffer=this.ba.za,this.s.connect(this.N),this.Nb=this.s,this.s.onended=this.Bc,this.s.loop=this.ka,x(this,this.kb),this.eb(),this.s.start(0,this.da),this.Ec=jc(this),this.Cc=this.da,this.W=!1)}Rc(){return super.Rc()*this.zd}pc(){this.zd=this.vb||this.jc()?0:1;x(this,this.kb)}Vc(a){a=!!a;this.ka!==a&&(this.ka=a,this.s&&(this.s.loop=a))}eb(){let a=this.Ca;this.vd&&(a*=this.A.Jc);this.s&&(this.s.playbackRate.value=a)}Uc(a){this.R||this.$()||(this.W?
this.da=a:(this.Mb(),this.da=a,this.kc()))}Sc(){return this.da}Wc(a){a?this.IsPlaying()?(this.Ma=!0,this.da=this.mb(),this.ka&&(this.da%=this.xa()),this.s.stop(0)):this.Ma=!1:this.Ma&&(kc(this),this.s=this.ia().createBufferSource(),this.s.buffer=this.ba.za,this.s.connect(this.N),this.Nb=this.s,this.s.onended=this.Bc,this.s.loop=this.ka,x(this,this.kb),this.eb(),this.s.start(0,this.da),this.Ec=jc(this),this.Cc=this.da,this.Ma=!1)}bd(a){super.bd(a);this.da=a.resumePosition}};"use strict";
function y(a){return a.g.createGain()}function z(a,b,c,d,e){b.cancelScheduledValues(0);if(0===e)b.value=c;else switch(a=a.g.currentTime,e+=a,d){case 0:b.setValueAtTime(c,e);break;case 1:b.setValueAtTime(b.value,a);b.linearRampToValueAtTime(c,e);break;case 2:b.setValueAtTime(b.value,a),b.exponentialRampToValueAtTime(c,e)}}class A{constructor(a){this.A=a;this.g=a.ia();this.le=-1;this.ea=this.Cd="";this.o=null}j(){this.g=null}Z(){}fa(){}Jb(){return{type:this.ea,tag:this.Cd,params:this.o}}}
self.Ge=class extends A{constructor(a,b,c,d,e,f,g){super(a);this.ea="filter";this.o=[b,c,d,e,f,g];this.C=y(this);this.i=y(this);this.i.gain.value=g;this.h=y(this);this.h.gain.value=1-g;this.L=this.g.createBiquadFilter();this.L.type=b;this.L.frequency.value=c;this.L.detune.value=d;this.L.Q.value=e;this.L.gain.vlaue=f;this.C.connect(this.L);this.C.connect(this.h);this.L.connect(this.i)}j(){this.C.disconnect();this.L.disconnect();this.i.disconnect();this.h.disconnect();super.j()}fa(a){this.i.disconnect();
this.i.connect(a);this.h.disconnect();this.h.connect(a)}Z(){return this.C}la(a,b,c,d){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.o[5]=b;z(this,this.i.gain,b,c,d);z(this,this.h.gain,1-b,c,d);break;case 1:this.o[1]=b;z(this,this.L.frequency,b,c,d);break;case 2:this.o[2]=b;z(this,this.L.detune,b,c,d);break;case 3:this.o[3]=b;z(this,this.L.Q,b,c,d);break;case 4:this.o[4]=b,z(this,this.L.gain,b,c,d)}}};
self.Ee=class extends A{constructor(a,b,c,d){super(a);this.ea="delay";this.o=[b,c,d];this.C=y(this);this.i=y(this);this.i.gain.value=d;this.h=y(this);this.h.gain.value=1-d;this.Zb=y(this);this.ja=this.g.createDelay(b);this.ja.delayTime.value=b;this.Sb=y(this);this.Sb.gain.value=c;this.C.connect(this.Zb);this.C.connect(this.h);this.Zb.connect(this.i);this.Zb.connect(this.ja);this.ja.connect(this.Sb);this.Sb.connect(this.Zb)}j(){this.C.disconnect();this.i.disconnect();this.h.disconnect();this.Zb.disconnect();
this.ja.disconnect();this.Sb.disconnect();super.j()}fa(a){this.i.disconnect();this.i.connect(a);this.h.disconnect();this.h.connect(a)}Z(){return this.C}la(a,b,c,d){const e=self.Ib.Nd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.o[2]=b;z(this,this.i.gain,b,c,d);z(this,this.h.gain,1-b,c,d);break;case 4:this.o[1]=e(b);z(this,this.Sb.gain,e(b),c,d);break;case 5:this.o[0]=b,z(this,this.ja.delayTime,b,c,d)}}};
self.De=class extends A{constructor(a,b,c,d){super(a);this.ea="convolution";this.o=[c,d];this.ae=this.$d="";this.C=y(this);this.i=y(this);this.i.gain.value=d;this.h=y(this);this.h.gain.value=1-d;this.Rb=this.g.createConvolver();this.Rb.normalize=c;this.Rb.buffer=b;this.C.connect(this.Rb);this.C.connect(this.h);this.Rb.connect(this.i)}j(){this.C.disconnect();this.Rb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}fa(a){this.i.disconnect();this.i.connect(a);this.h.disconnect();this.h.connect(a)}Z(){return this.C}la(a,
b,c,d){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.o[1]=b,z(this,this.i.gain,b,c,d),z(this,this.h.gain,1-b,c,d)}}Jb(){const a=super.Jb();a.bufferOriginalUrl=this.$d;a.bufferUrl="";a.bufferType=this.ae;return a}};
self.He=class extends A{constructor(a,b,c,d,e,f){super(a);this.ea="flanger";this.o=[b,c,d,e,f];this.C=y(this);this.h=y(this);this.h.gain.value=1-f/2;this.i=y(this);this.i.gain.value=f/2;this.Tb=y(this);this.Tb.gain.value=e;this.ja=this.g.createDelay(b+c);this.ja.delayTime.value=b;this.I=this.g.createOscillator();this.I.frequency.value=d;this.X=y(this);this.X.gain.value=c;this.C.connect(this.ja);this.C.connect(this.h);this.ja.connect(this.i);this.ja.connect(this.Tb);this.Tb.connect(this.ja);this.I.connect(this.X);
this.X.connect(this.ja.delayTime);this.I.start(0)}j(){this.I.stop(0);this.C.disconnect();this.ja.disconnect();this.I.disconnect();this.X.disconnect();this.h.disconnect();this.i.disconnect();this.Tb.disconnect();super.j()}fa(a){this.i.disconnect();this.i.connect(a);this.h.disconnect();this.h.connect(a)}Z(){return this.C}la(a,b,c,d){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.o[4]=b;z(this,this.i.gain,b/2,c,d);z(this,this.h.gain,1-b/2,c,d);break;case 6:this.o[1]=b/1E3;z(this,this.X.gain,b/
1E3,c,d);break;case 7:this.o[2]=b;z(this,this.I.frequency,b,c,d);break;case 8:this.o[3]=b/100,z(this,this.Tb.gain,b/100,c,d)}}};
self.Je=class extends A{constructor(a,b,c,d,e,f,g){super(a);this.ea="phaser";this.o=[b,c,d,e,f,g];this.C=y(this);this.h=y(this);this.h.gain.value=1-g/2;this.i=y(this);this.i.gain.value=g/2;this.L=this.g.createBiquadFilter();this.L.type="allpass";this.L.frequency.value=b;this.L.detune.value=c;this.L.Q.value=d;this.I=this.g.createOscillator();this.I.frequency.value=f;this.X=y(this);this.X.gain.value=e;this.C.connect(this.L);this.C.connect(this.h);this.L.connect(this.i);this.I.connect(this.X);this.X.connect(this.L.frequency);
this.I.start(0)}j(){this.I.stop(0);this.C.disconnect();this.L.disconnect();this.I.disconnect();this.X.disconnect();this.h.disconnect();this.i.disconnect();super.j()}fa(a){this.i.disconnect();this.i.connect(a);this.h.disconnect();this.h.connect(a)}Z(){return this.C}la(a,b,c,d){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.o[5]=b;z(this,this.i.gain,b/2,c,d);z(this,this.h.gain,1-b/2,c,d);break;case 1:this.o[0]=b;z(this,this.L.frequency,b,c,d);break;case 2:this.o[1]=b;z(this,this.L.detune,b,c,
d);break;case 3:this.o[2]=b;z(this,this.L.Q,b,c,d);break;case 6:this.o[3]=b;z(this,this.X.gain,b,c,d);break;case 7:this.o[4]=b,z(this,this.I.frequency,b,c,d)}}};self.Ie=class extends A{constructor(a,b){super(a);this.ea="gain";this.o=[b];this.l=y(this);this.l.gain.value=b}j(){this.l.disconnect();super.j()}fa(a){this.l.disconnect();this.l.connect(a)}Z(){return this.l}la(a,b,c,d){const e=self.Ib.Nd;switch(a){case 4:this.o[0]=e(b),z(this,this.l.gain,e(b),c,d)}}};
self.Le=class extends A{constructor(a,b){super(a);this.ea="stereopan";this.o=[b];this.l=this.g.createStereoPanner();this.l.pan.value=b}j(){this.l.disconnect();super.j()}fa(a){this.l.disconnect();this.l.connect(a)}Z(){return this.l}la(a,b,c,d){b=Math.min(Math.max(b/100,-1),1);switch(a){case 9:this.o[0]=b,z(this,this.l.pan,b,c,d)}}};
self.Me=class extends A{constructor(a,b,c){super(a);this.ea="tremolo";this.o=[b,c];this.l=y(this);this.l.gain.value=1-c/2;this.I=this.g.createOscillator();this.I.frequency.value=b;this.X=y(this);this.X.gain.value=c/2;this.I.connect(this.X);this.X.connect(this.l.gain);this.I.start(0)}j(){this.I.stop(0);this.I.disconnect();this.X.disconnect();this.l.disconnect();super.j()}fa(a){this.l.disconnect();this.l.connect(a)}Z(){return this.l}la(a,b,c,d){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.o[1]=
b;z(this,this.l.gain,1-b/2,c,d);z(this,this.X.gain,b/2,c,d);break;case 7:this.o[0]=b,z(this,this.I.frequency,b,c,d)}}};
self.Ke=class extends A{constructor(a,b,c){super(a);this.ea="ringmod";this.o=[b,c];this.C=y(this);this.i=y(this);this.i.gain.value=c;this.h=y(this);this.h.gain.value=1-c;this.dc=y(this);this.dc.gain.value=0;this.I=this.g.createOscillator();this.I.frequency.value=b;this.I.connect(this.dc.gain);this.I.start(0);this.C.connect(this.dc);this.C.connect(this.h);this.dc.connect(this.i)}j(){this.I.stop(0);this.I.disconnect();this.dc.disconnect();this.C.disconnect();this.i.disconnect();this.h.disconnect();
super.j()}fa(a){this.i.disconnect();this.i.connect(a);this.h.disconnect();this.h.connect(a)}Z(){return this.C}la(a,b,c,d){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.o[1]=b;z(this,this.i.gain,b,c,d);z(this,this.h.gain,1-b,c,d);break;case 7:this.o[0]=b,z(this,this.I.frequency,b,c,d)}}};
self.Fe=class extends A{constructor(a,b,c,d,e,f){super(a);this.ea="distortion";this.o=[b,c,d,e,f];this.C=y(this);this.Gc=y(this);this.Fc=y(this);a=d;.01>a&&(a=.01);this.Gc.gain.value=a;this.Fc.gain.value=Math.pow(1/a,.6)*e;this.i=y(this);this.i.gain.value=f;this.h=y(this);this.h.gain.value=1-f;this.Kc=this.g.createWaveShaper();this.ld=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,a=1.05*c*b-b,d=0>f?-f:f,d<b?a=d:(d=1-Math.exp(-(1/a)*(d-b)),a=b+a*d),f=a*(0>f?-1:1),this.ld[32768+e]=f,this.ld[32768-
e-1]=-f;this.Kc.curve=this.ld;this.C.connect(this.Gc);this.C.connect(this.h);this.Gc.connect(this.Kc);this.Kc.connect(this.Fc);this.Fc.connect(this.i)}j(){this.C.disconnect();this.Gc.disconnect();this.Kc.disconnect();this.Fc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}fa(a){this.i.disconnect();this.i.connect(a);this.h.disconnect();this.h.connect(a)}Z(){return this.C}la(a,b,c,d){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.o[4]=b,z(this,this.i.gain,b,c,d),z(this,this.h.gain,
1-b,c,d)}}};self.Ce=class extends A{constructor(a,b,c,d,e,f){super(a);this.ea="compressor";this.o=[b,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=b;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}fa(a){this.l.disconnect();this.l.connect(a)}Z(){return this.l}la(){}};
self.Be=class extends A{constructor(a,b,c){super(a);this.ea="analyser";this.o=[b,c];this.l=this.g.createAnalyser();this.l.fftSize=b;this.l.smoothingTimeConstant=c;this.he=new Float32Array(this.l.frequencyBinCount);this.we=new Uint8Array(b);this.ue=this.Bb=0;a=this.A;a.rb.add(this);Nb(a)}j(){this.A.rb.delete(this);this.l.disconnect();super.j()}pb(){this.l.getFloatFrequencyData(this.he);this.l.getByteTimeDomainData(this.we);const a=this.l.fftSize;let b=this.Bb=0;for(var c=0;c<a;++c){let d=(this.we[c]-
128)/128;0>d&&(d=-d);this.Bb<d&&(this.Bb=d);b+=d*d}c=self.Ib.cf;this.Bb=c(this.Bb);this.ue=c(Math.sqrt(b/a))}fa(a){this.l.disconnect();this.l.connect(a)}Z(){return this.l}la(){}};"use strict";const lc={};let B=null,mc=null;const nc={banner:"ca-app-pub-3940256099942544/2934735716",interstitial:"ca-app-pub-3940256099942544/4411468910",rewarded:"ca-app-pub-3940256099942544/1712485313",rewardedInterstitial:"ca-app-pub-3940256099942544/6978759866"};let oc=!1;
function pc(a,b){lc[a]=b;self.admob.configRequest(lc)}async function qc(){if("android"===self.cordova.platformId)return self.Jd(self.device.uuid).toUpperCase();if("ios"===self.cordova.platformId){const a=await self.cordova.plugins.idfa.getInfo();if(!a.trackingLimited)return oc=!0,self.Jd(a.idfa).toUpperCase()}}
self.Ya={F:function(a,b){a(null,b)},v:function(a,b){a(b,null)},ta:async function(a,b){b="undefined"!==typeof b?b:B.debug;return mc?mc:mc=new Promise(c=>{document.addEventListener("deviceready",async()=>{try{const d=setTimeout(()=>{c(!1);a("failure to initialize",null)},5E3);await self.admob.start();clearTimeout(d);if(b){const e=await qc();pc("testDeviceIds",[e])}c(!0)}catch(d){c(!1),a("Initialization failure",null)}})})},Xc:pc,df:function(a,b,c,d,e,f,g){B||(B={id:a,Tf:b,Sf:c,Wf:d,kg:e,debug:f,Nf:g},
Object.freeze(B))},Xe:function(){return!!B},ic:function(a,b){if("android"===self.cordova.platformId)return a;if("ios"===self.cordova.platformId){const c=!!nc[b];return B.debug&&!oc&&c?(console.log("[C3 advert]","USING TEST AD UNITS"),nc[b]):a}},get Za(){return B},get ff(){return qc()}};"use strict";const rc=self.Ya,C=rc.F,D=rc.v,F={get S(){return self.admob.Events.bannerLoad},get T(){return self.admob.Events.bannerLoadFail}};
async function sc(a){var b=G;if(!b.D)return D(a,"banner ad not created");if(b.G)return D(a,"banner ad still loading");if(!b.H)return C(a,"banner ad not being shown");await b.D.hide();b.H=!1;C(a,"banner ad hidden")}
class tc{constructor(a,b,c,d){if(!a)return D(d,"Unit ID not specified");if(!b)return D(d,"Ad size not specified");if(!c)return D(d,"Ad position not specified");this.fb=a;this.Jf=c;this.Na="";switch(b){case "portrait":this.Na=5;break;case "landscape":this.Na=5;break;case "standard":this.Na=0;break;case "large":this.Na=1;break;case "medium":this.Na=2;break;case "full":this.Na=3;break;case "leaderboard":this.Na=4;break;default:this.Na=5}this.D=null;this.H=this.G=!1;this.wb=this.xd=this.Hc=null}j(){this.Hc&&
this.Hc();this.D=this.wb=this.xd=this.Hc=null}U(a,b){if(this.D)return C(b,"banner ad loaded");uc.call(this,b);a={adUnitId:rc.ic(this.fb,"banner"),size:this.Na,position:this.Jf,offset:0,npa:"NON_PERSONALIZED"===a?"1":"0"};this.D=new self.admob.BannerAd(a);this.xd=new Promise(c=>this.wb=c);this.D.load()}async Sa(a){this.D?this.G?D(a,"banner ad still loading"):this.H?C(a,"banner ad already shown"):(await this.D.show(),this.H=!0,C(a,"banner shown")):D(a,"banner ad not created")}}
function uc(a){const b=()=>{this.G=!1;C(a,"banner ad loaded");document.removeEventListener(F.S,b);document.removeEventListener(F.T,c);this.wb&&this.wb()},c=()=>{this.D=null;this.G=!1;D(a,"banner ad failed to load");document.removeEventListener(F.S,b);document.removeEventListener(F.T,c);this.wb&&this.wb()};this.Hc=()=>{document.removeEventListener(F.S,b);document.removeEventListener(F.T,c);document.removeEventListener(F.S,b);document.removeEventListener(F.T,c)};document.addEventListener(F.S,b);document.addEventListener(F.T,
c)}self.Ne=tc;"use strict";const vc=self.Ya,wc=vc.F,xc=vc.v,H={get S(){return self.admob.Events.interstitialLoad},get T(){return self.admob.Events.interstitialLoadFail},get ra(){return self.admob.Events.interstitialShow},get sa(){return self.admob.Events.interstitialShowFail},get Fa(){return self.admob.Events.interstitialDismiss}};
class yc{constructor(a,b){if(!a)return xc(b,"Unit ID not specified");this.fb=a;this.D=null;this.O=this.H=this.G=!1;this.ha=null;this.m=this.J();document.addEventListener(H.Fa,async()=>{this.H=!1;this.G=!0;this.O=!1;this.m=null;this.m=this.J();zc.call(this);self.C3MobileAdvertsAPI.real.resumeRuntime();await this.D.load()})}J(){return this.m?this.m:this.m=new Promise(a=>{this.ha=a})}Qa(a){this.O=a;this.ha&&this.ha(a);this.ha=this.m=null;this.m=this.J()}U(a,b){a={adUnitId:vc.ic(this.fb,"interstitial"),
npa:"NON_PERSONALIZED"===a?"1":"0"};this.G=!0;this.O=this.H=!1;this.m=null;this.m=this.J();this.D=new self.admob.InterstitialAd(a);zc.call(this,b);this.D.load()}Pa(a,b){a?vc.F(b,"interstitial ad load"):vc.v(b,"interstitial ad failed to load")}async Sa(a){this.D?this.H?wc(a,"interstitial ad already shown"):(this.G&&await this.J(),await (async()=>{this.O?(Ac.call(this,a),await this.D.show()):(zc.call(this),this.O=!1,this.m=null,this.D.load(),await this.J(),this.O?(Ac.call(this,a),await this.D.show()):
xc(a,"interstitial ad failed to load"))})()):xc(a,"interstitial ad not created")}}function zc(a){const b=()=>{this.G=!1;this.Qa(!0);a&&wc(a,"interstitial ad load");document.removeEventListener(H.S,b);document.removeEventListener(H.T,c)},c=()=>{this.G=!1;this.Qa(!1);a&&xc(a,"interstitial ad failed to load");document.removeEventListener(H.S,b);document.removeEventListener(H.T,c)};document.addEventListener(H.S,b);document.addEventListener(H.T,c)}
function Ac(a){const b=()=>{this.H=!0;self.C3MobileAdvertsAPI.real.suspendRuntime();a&&wc(a,"interstitial ad show");document.removeEventListener(H.ra,b);document.removeEventListener(H.sa,c)},c=()=>{this.H=!1;a&&xc(a,"interstitial ad failed to show");document.removeEventListener(H.ra,b);document.removeEventListener(H.sa,c)};document.addEventListener(H.ra,b);document.addEventListener(H.sa,c)}self.Re=yc;"use strict";
const Bc=self.Ya,Cc=Bc.F,Dc=Bc.v,I={get S(){return self.admob.Events.rewardedLoad},get T(){return self.admob.Events.rewardedLoadFail},get ra(){return self.admob.Events.rewardedShow},get sa(){return self.admob.Events.rewardedShowFail},get Fa(){return self.admob.Events.rewardedDismiss},get ab(){return self.admob.Events.rewardedReward}};
class Ec{constructor(a,b){if(!a)return Dc(b,"Unit ID not specified");this.fb=a;this.D=null;this.O=this.H=this.G=!1;this.ha=null;this.m=this.J();this.va=null}J(){return this.m?this.m:this.m=new Promise(a=>{this.ha=a})}Qa(a){this.O=a;this.ha&&this.ha(a);this.ha=this.m=null;this.m=this.J()}U(a,b){a={adUnitId:Bc.ic(this.fb,"rewarded"),npa:"NON_PERSONALIZED"===a?"1":"0"};this.G=!0;this.O=this.H=!1;this.m=null;this.m=this.J();this.D=new self.admob.RewardedAd(a);Fc.call(this,b);this.D.load()}Pa(a,b){a?Bc.F(b,
"rewarded ad load"):Bc.v(b,"rewarded ad failed to load")}async Sa(a){this.D?this.H?Cc(a,"rewarded ad already shown"):(this.G&&await this.J(),await (async()=>{this.O?(Gc.call(this,a),await this.D.show()):(Fc.call(this),this.O=!1,this.m=null,this.D.load(),await this.J(),this.O?(Gc.call(this,a),await this.D.show()):Dc(a,"rewarded ad failed to load"))})()):Dc(a,"rewarded ad not created")}}
function Fc(a){const b=()=>{this.G=!1;this.Qa(!0);a&&Cc(a,"rewarded ad load");document.removeEventListener(I.S,b);document.removeEventListener(I.T,c)},c=()=>{this.G=!1;this.Qa(!1);a&&Dc(a,"rewarded ad failed to load");document.removeEventListener(I.S,b);document.removeEventListener(I.T,c)};document.addEventListener(I.S,b);document.addEventListener(I.T,c)}
function Gc(a){const b=()=>{this.H=!0;self.C3MobileAdvertsAPI.real.suspendRuntime()},c=f=>{this.va=f.reward},d=()=>{this.H=!1;a&&Dc(a,"rewarded ad failed to show");document.removeEventListener(I.ra,b);document.removeEventListener(I.sa,d);document.removeEventListener(I.ab,c);document.removeEventListener(I.Fa,e)},e=()=>{if(null!==this.va){const f=String(this.va.type),g=String(this.va.amount);a&&Cc(a,JSON.stringify([f,g]))}else a&&Dc(a,"closed with no reward");this.va=null;this.H=!1;this.G=!0;this.O=
!1;this.m=null;this.m=this.J();Fc.call(this);self.C3MobileAdvertsAPI.real.resumeRuntime();this.D.load();document.removeEventListener(I.ra,b);document.removeEventListener(I.sa,d);document.removeEventListener(I.ab,c);document.removeEventListener(I.Fa,e)};document.addEventListener(I.ra,b);document.addEventListener(I.sa,d);document.addEventListener(I.ab,c);document.addEventListener(I.Fa,e)}self.Se=Ec;"use strict";
const Hc=self.Ya,Ic=Hc.F,Jc=Hc.v,J={get S(){return self.admob.Events.rewardedInterstitialLoad},get T(){return self.admob.Events.rewardedInterstitialLoadFail},get ra(){return self.admob.Events.rewardedInterstitialShow},get sa(){return self.admob.Events.rewardedInterstitialShowFail},get Fa(){return self.admob.Events.rewardedInterstitialDismiss},get ab(){return self.admob.Events.rewardedInterstitialReward}};
class Kc{constructor(a,b){if(!a)return Jc(b,"Unit ID not specified");this.fb=a;this.D=null;this.O=this.H=this.G=!1;this.ha=null;this.m=this.J();this.va=null}J(){return this.m?this.m:this.m=new Promise(a=>{this.ha=a})}Qa(a){this.O=a;this.ha&&this.ha(a);this.ha=this.m=null;this.m=this.J()}U(a,b){a={adUnitId:Hc.ic(this.fb,"rewardedInterstitial"),npa:"NON_PERSONALIZED"===a?"1":"0"};this.G=!0;this.O=this.H=!1;this.m=null;this.m=this.J();this.D=new self.admob.RewardedInterstitialAd(a);Lc.call(this,b);this.D.load()}Pa(a,
b){a?Hc.F(b,"rewarded interstitial ad load"):Hc.v(b,"rewarded interstitial ad failed to load")}async Sa(a){this.D?this.H?Ic(a,"rewarded interstitial ad already shown"):(this.G&&await this.J(),await (async()=>{this.O?(Mc.call(this,a),await this.D.show()):(Lc.call(this),this.O=!1,this.m=null,this.D.load(),await this.J(),this.O?(Mc.call(this,a),await this.D.show()):Jc(a,"rewarded interstitial ad failed to load"))})()):Jc(a,"rewarded interstitial ad not created")}}
function Lc(a){const b=()=>{this.G=!1;this.Qa(!0);a&&Ic(a,"rewarded interstitial ad load");document.removeEventListener(J.S,b);document.removeEventListener(J.T,c)},c=()=>{this.G=!1;this.Qa(!1);a&&Jc(a,"rewarded interstitial ad failed to load");document.removeEventListener(J.S,b);document.removeEventListener(J.T,c)};document.addEventListener(J.S,b);document.addEventListener(J.T,c)}
function Mc(a){const b=()=>{this.H=!0;self.C3MobileAdvertsAPI.real.suspendRuntime()},c=f=>{this.va=f.reward},d=()=>{this.H=!1;a&&Jc(a,"rewarded interstitial ad failed to show");document.removeEventListener(J.ra,b);document.removeEventListener(J.sa,d);document.removeEventListener(J.ab,c);document.removeEventListener(J.Fa,e)},e=()=>{if(null!==this.va){const f=String(this.va.type),g=String(this.va.amount);a&&Ic(a,JSON.stringify([f,g]))}else a&&Jc(a,"closed with no reward");this.va=null;this.H=!1;this.G=
!0;this.O=!1;this.m=null;this.m=this.J();Lc.call(this);self.C3MobileAdvertsAPI.real.resumeRuntime();this.D.load();document.removeEventListener(J.ra,b);document.removeEventListener(J.sa,d);document.removeEventListener(J.ab,c);document.removeEventListener(J.Fa,e)};document.addEventListener(J.ra,b);document.addEventListener(J.sa,d);document.addEventListener(J.ab,c);document.addEventListener(J.Fa,e)}self.Te=Kc;"use strict";
const Nc=self.Ya,Oc=Nc.F,Pc=Nc.v,Qc=self.cordova?"ios"===self.cordova.platformId:!1,Rc=self.cordova?"android"===self.cordova.platformId:!1;async function Sc(){Qc&&await self.admob.requestTrackingAuthorization()}
async function Tc(a){if(Rc)return a.Ea="not-determined";const b=self.cordova.plugins.idfa,c=await b.getInfo();if(!c.trackingLimited)return a.Ea="authorized";switch(c.trackingPermission){case b.TRACKING_PERMISSION_NOT_DETERMINED:return a.Ea="not-determined";case b.TRACKING_PERMISSION_RESTRICTED:return a.Ea="denied";case b.TRACKING_PERMISSION_DENIED:return a.Ea="denied";case b.TRACKING_PERMISSION_AUTHORIZED:return a.Ea="authorized"}}async function Uc(a){await Vc(a,"always",!0)}
async function Wc(a){var b=K;Rc?Oc(a,"not-determined"):Qc&&(await Xc.call(b),"true"===b.Ia?await Sc():(await Tc(b),"not-determined"===b.Ea&&(await Yc.call(b),b.pd?await Uc(b):await Sc())),await Tc(b),Oc(a,b.Ea))}async function Zc(a,b,c){return await $c.call(K,a,b,d=>{d?"object"===typeof d?Pc(c,d.message):Pc(c,d):Pc(c,"requestInfoUpdate error")})}async function bd(a,b){await $c.call(K,a,b)}
async function Vc(a,b,c=!1){await cd.call(a);switch(b){case "eu":c=await Yc.call(a);dd.call(a)&&c&&await (await self.consent.loadForm()).show();break;case "always":b=await Yc.call(a);const d=await Xc.call(a);b&&"true"===d?await (await self.consent.loadForm()).show():b&&c&&await (await self.consent.loadForm()).show()}await cd.call(a);await Xc.call(a);await ed.call(a)}async function fd(a){await cd.call(a);await Xc.call(a);await ed.call(a)}
async function gd(a){var b=K;await Tc(b);Oc(a,`${b.sb}&&${b.Ea}&&${b.Ia}`)}async function hd(a,b){Pc(a,b)}async function id(a){var b=K;await fd(b);await Tc(b);Oc(a,`${b.sb}&&${b.Ea}&&${b.Ia}`)}class jd{constructor(){this.aa="UNKNOWN";this.Ia="";this.Qb=0;this.sb="UNKNOWN";this.Ea="not-determined";this.pd=!1}async Rd(){Nc.Za.debug&&await self.consent.reset()}}async function Yc(){return this.pd=await self.consent.getFormStatus()===self.consent.FormStatus.Available}
async function cd(){this.Qb=await self.consent.getConsentStatus();switch(this.Qb){case 1:return this.sb="REQUIRED";case 2:return this.sb="NOT_REQUIRED";case 3:return this.sb="OBTAINED";case 0:return this.sb="UNKNOWN"}}function dd(){switch(this.Qb){case 1:return!0;case 2:return!1;case 3:return!1;case 0:return!0}}function ed(){switch(this.Qb){case 1:return this.aa="NON_PERSONALIZED";case 2:return this.aa="PERSONALIZED";case 3:return this.aa="PERSONALIZED";case 0:return this.aa="NON_PERSONALIZED"}}
async function Xc(){if(Rc)switch(this.Qb){case 1:return this.Ia="true";case 2:return this.Ia="false";case 3:return this.Ia="true";case 0:return this.Ia="true"}if(Qc)return await kd.call(this)?this.Ia="true":this.Ia="false"}async function kd(){return new Promise(a=>{self.NativeStorage.getInt("IABTCF_gdprApplies",b=>a(b),()=>a(1))})}
async function $c(a,b,c){let d="",e=null;if(a){switch(b){case "EEA":d=self.consent.DebugGeography.EEA;break;case "NOT_EEA":d=self.consent.DebugGeography.NotEEA;break;default:d=self.consent.DebugGeography.Disabled}e=[await Nc.ff]}try{return a?await self.consent.requestInfoUpdate({hg:d,lg:e}):await self.consent.requestInfoUpdate(),!0}catch(f){return c&&c(f),!1}}self.Oe=new jd;"use strict";
const ld=(a,b)=>{let c=a[0],d=a[1],e=a[2],f=a[3];c=L(d&e|~d&f,c,d,b[0],7,-680876936);f=L(c&d|~c&e,f,c,b[1],12,-389564586);e=L(f&c|~f&d,e,f,b[2],17,606105819);d=L(e&f|~e&c,d,e,b[3],22,-1044525330);c=L(d&e|~d&f,c,d,b[4],7,-176418897);f=L(c&d|~c&e,f,c,b[5],12,1200080426);e=L(f&c|~f&d,e,f,b[6],17,-1473231341);d=L(e&f|~e&c,d,e,b[7],22,-45705983);c=L(d&e|~d&f,c,d,b[8],7,1770035416);f=L(c&d|~c&e,f,c,b[9],12,-1958414417);e=L(f&c|~f&d,e,f,b[10],17,-42063);d=L(e&f|~e&c,d,e,b[11],22,-1990404162);c=L(d&e|~d&
f,c,d,b[12],7,1804603682);f=L(c&d|~c&e,f,c,b[13],12,-40341101);e=L(f&c|~f&d,e,f,b[14],17,-1502002290);d=L(e&f|~e&c,d,e,b[15],22,1236535329);c=L(d&f|e&~f,c,d,b[1],5,-165796510);f=L(c&e|d&~e,f,c,b[6],9,-1069501632);e=L(f&d|c&~d,e,f,b[11],14,643717713);d=L(e&c|f&~c,d,e,b[0],20,-373897302);c=L(d&f|e&~f,c,d,b[5],5,-701558691);f=L(c&e|d&~e,f,c,b[10],9,38016083);e=L(f&d|c&~d,e,f,b[15],14,-660478335);d=L(e&c|f&~c,d,e,b[4],20,-405537848);c=L(d&f|e&~f,c,d,b[9],5,568446438);f=L(c&e|d&~e,f,c,b[14],9,-1019803690);
e=L(f&d|c&~d,e,f,b[3],14,-187363961);d=L(e&c|f&~c,d,e,b[8],20,1163531501);c=L(d&f|e&~f,c,d,b[13],5,-1444681467);f=L(c&e|d&~e,f,c,b[2],9,-51403784);e=L(f&d|c&~d,e,f,b[7],14,1735328473);d=L(e&c|f&~c,d,e,b[12],20,-1926607734);c=L(d^e^f,c,d,b[5],4,-378558);f=L(c^d^e,f,c,b[8],11,-2022574463);e=L(f^c^d,e,f,b[11],16,1839030562);d=L(e^f^c,d,e,b[14],23,-35309556);c=L(d^e^f,c,d,b[1],4,-1530992060);f=L(c^d^e,f,c,b[4],11,1272893353);e=L(f^c^d,e,f,b[7],16,-155497632);d=L(e^f^c,d,e,b[10],23,-1094730640);c=L(d^
e^f,c,d,b[13],4,681279174);f=L(c^d^e,f,c,b[0],11,-358537222);e=L(f^c^d,e,f,b[3],16,-722521979);d=L(e^f^c,d,e,b[6],23,76029189);c=L(d^e^f,c,d,b[9],4,-640364487);f=L(c^d^e,f,c,b[12],11,-421815835);e=L(f^c^d,e,f,b[15],16,530742520);d=L(e^f^c,d,e,b[2],23,-995338651);c=L(e^(d|~f),c,d,b[0],6,-198630844);f=L(d^(c|~e),f,c,b[7],10,1126891415);e=L(c^(f|~d),e,f,b[14],15,-1416354905);d=L(f^(e|~c),d,e,b[5],21,-57434055);c=L(e^(d|~f),c,d,b[12],6,1700485571);f=L(d^(c|~e),f,c,b[3],10,-1894986606);e=L(c^(f|~d),e,
f,b[10],15,-1051523);d=L(f^(e|~c),d,e,b[1],21,-2054922799);c=L(e^(d|~f),c,d,b[8],6,1873313359);f=L(d^(c|~e),f,c,b[15],10,-30611744);e=L(c^(f|~d),e,f,b[6],15,-1560198380);d=L(f^(e|~c),d,e,b[13],21,1309151649);c=L(e^(d|~f),c,d,b[4],6,-145523070);f=L(d^(c|~e),f,c,b[11],10,-1120210379);e=L(c^(f|~d),e,f,b[2],15,718787259);d=L(f^(e|~c),d,e,b[9],21,-343485551);a[0]=c+a[0]&4294967295;a[1]=d+a[1]&4294967295;a[2]=e+a[2]&4294967295;a[3]=f+a[3]&4294967295},L=(a,b,c,d,e,f)=>{b=(b+a&4294967295)+(d+f&4294967295)&
4294967295;return(b<<e|b>>>32-e)+c&4294967295},md=a=>{const b=a.length,c=[1732584193,-271733879,-1732584194,271733878];let d;for(d=64;d<=a.length;d+=64){var e=a.substring(d-64,d);const f=[];for(let g=0;64>g;g+=4)f[g>>2]=e.charCodeAt(g)+(e.charCodeAt(g+1)<<8)+(e.charCodeAt(g+2)<<16)+(e.charCodeAt(g+3)<<24);ld(c,f)}a=a.substring(d-64);e=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(d=0;d<a.length;d++)e[d>>2]|=a.charCodeAt(d)<<(d%4<<3);e[d>>2]|=128<<(d%4<<3);if(55<d)for(ld(c,e),d=0;16>d;d++)e[d]=0;e[14]=8*b;
ld(c,e);return c},nd="0123456789abcdef".split(""),od=a=>{for(let c=0;c<a.length;c++){var b=a[c];let d="";for(let e=0;4>e;e++)d+=nd[b>>8*e+4&15]+nd[b>>8*e&15];a[c]=d}return a.join("")};od(md("hello"));self.Jd=a=>od(md(a));"use strict";const M=self.Ya,K=self.Oe,pd=self.Ne,qd=self.Re,rd=self.Se,sd=self.Te;let G=null,N=null,P=null,Q=null,R=null;
const td={CreateBannerAdvert:async(a,b,c,d,e,f)=>{await M.ta(f,c)&&(e&&G&&(await G.xd,await sc(()=>!0),G.j(),G=null),c=await K.aa,G||(G=new pd(a,b,d,f)),G.U(c,f))},ShowBannerAdvert:async a=>{if(!G)return M.v(a,"banner ad not created");G.Sa(a)},HideBannerAdvert:async a=>{if(!G)return M.v(a,"banner ad not created");sc(a)},CreateInterstitialAdvert:async(a,b,c)=>{if(N){if(N.H)return M.F(c,"interstitial ad already showing");N.G?(a=await N.J(),N.Pa(a,c)):(a=await K.aa,N.U(a,c))}else await M.ta(c,b)&&(b=
await K.aa,N=new qd(a,c),N.U(b,c))},ShowInterstitialAdvert:async a=>{if(!N)return M.v(a,"interstitial ad not created");N.Sa(a)},CreateVideoAdvert:async(a,b,c)=>{if(P||Q){if(Q){if(Q.H)return M.F(c,"rewarded ad already showing");Q.G?(a=await Q.J(),Q.Pa(a,c)):(a=await K.aa,Q.U(a,c));return}if(P){if(P.H)return M.F(c,"rewarded ad already showing");P.G?(a=await P.J(),P.Pa(a,c)):(a=await K.aa,P.U(a,c));return}}await M.ta(c,b)&&(b=await K.aa,P=new rd(a,c),P.U(b,c))},ShowVideoAdvert:async a=>{if(!P)return M.v(a,
"video ad not created");P.Sa(a)},CreateRewardedAdvert:async(a,b,c)=>{if(Q||P){if(Q){if(Q.H)return M.F(c,"rewarded ad already showing");Q.G?(a=await Q.J(),Q.Pa(a,c)):(a=await K.aa,Q.U(a,c));return}if(P){if(P.H)return M.F(c,"rewarded ad already showing");P.G?(a=await P.J(),P.Pa(a,c)):(a=await K.aa,P.U(a,c));return}}await M.ta(c,b)&&(b=await K.aa,Q=new rd(a,c),Q.U(b,c))},ShowRewardedAdvert:async a=>{if(!Q)return M.v(a,"rewarded ad not created");Q.Sa(a)},CreateRewardedInterstitialAdvert:async(a,b,c)=>
{if(R){if(R.H)return M.F(c,"rewarded interstitial ad already showing");R.G?(a=await R.J(),R.Pa(a,c)):(a=await K.aa,R.U(a,c))}else await M.ta(c,b)&&(b=await K.aa,R=new sd(a,c),R.U(b,c))},ShowRewardedInterstitialAdvert:async a=>{if(!R)return M.v(a,"rewarded interstitial ad not created");R.Sa(a)},Configure:async(a,b,c,d,e,f,g,h,l)=>{const r=!M.Xe();M.df(a,b,c,d,e,f,g);if(!await M.ta(l,f))return hd(l,"failure to initialize");r&&await K.Rd();if(!await Zc(f,g,l))return hd(l,"failure to update consent information");
r?h?await Vc(K,"eu"):await fd(K):await Vc(K,"always");await gd(l)},RequestConsent:async a=>{td.Configure(M.Za.id,M.Za.Tf,M.Za.Sf,M.Za.Wf,"always",M.Za.debug,M.Za.Nf,!1,a)},SetMaxAdContentRating:async(a,b)=>{if(await M.ta(b)){if(!a)return M.v(b,"Label not specified");try{M.Xc("maxAdContentRating",a),M.F(b,"")}catch(c){M.v(b,"invalid label")}}},TagForChildDirectedTreatment:async(a,b)=>{if(await M.ta(b))try{M.Xc("tagForChildDirectedTreatment",1===a?!0:!1),M.F(b,"")}catch(c){M.v(b,"invalid label")}},
TagForUnderAgeOfConsent:async(a,b)=>{if(await M.ta(b))try{M.Xc("tagForUnderAgeOfConsent",1===a?!0:!1),M.F(b,"")}catch(c){M.v(b,"invalid label")}},RequestIDFA:async a=>{await M.ta(a)&&Wc(a)},StatusUpdate:async(a,b,c)=>{if(!await M.ta(c,a))return hd(c,"failure to initialize");await bd(a,b);await id(c)}};self.C3MobileAdvertsAPI||(self.C3MobileAdvertsAPI={});self.C3MobileAdvertsAPI.real=td;"use strict";const U={},V=()=>new Promise(a=>setTimeout(a,50));let ud=null,vd=null,wd=null,xd=null,yd=null;
function X(a,b){const c=b.slice(0,-1);b=b[b.length-1];console.log(a,c);return[c,b]}U.CreateBannerAdvert=async(...a)=>{[,a]=X("CreateBannerAdvert",a);await V();ud?a("Banner already exists"):(ud="ready",a(null,"Created banner"))};U.ShowBannerAdvert=async(...a)=>{[,a]=X("ShowBannerAdvert",a);await V();"ready"!=ud?a("Banner cannot be shown"):(ud="shown",a(null,"Showed banner"))};
U.HideBannerAdvert=async(...a)=>{[,a]=X("HideBannerAdvert",a);await V();"shown"!=ud?a("Banner cannot be hidden"):(ud=null,a(null,"Hid banner"))};U.CreateInterstitialAdvert=async(...a)=>{[,a]=X("CreateInterstitialAdvert",a);await V();vd?a("Intersitial already exists"):(vd="ready",a(null,"Created interstitial"))};U.ShowInterstitialAdvert=async(...a)=>{[,a]=X("ShowInterstitialAdvert",a);await V();"ready"!=vd?a("Cannot show interstitial"):(vd=null,a(null,"Interstitial shown"))};
U.CreateVideoAdvert=async(...a)=>{[,a]=X("CreateVideoAdvert",a);await V();wd?a("Video already exists"):(wd="ready",a(null,"Created video"))};U.ShowVideoAdvert=async(...a)=>{[,a]=X("ShowVideoAdvert",a);await V();"ready"!=wd?a("Cannot show video"):(wd=null,a(null,'["example type", 20]'))};U.CreateRewardedAdvert=async(...a)=>{[,a]=X("CreateRewardedAdvert",a);await V();xd?a("Rewarded already exists"):(xd="ready",a(null,"Created rewarded"))};
U.ShowRewardedAdvert=async(...a)=>{[,a]=X("ShowRewardedAdvert",a);await V();"ready"!=xd?a("Cannot show rewarded"):(xd=null,a(null,'["example type", 20]'))};U.CreateRewardedInterstitialAdvert=async(...a)=>{[,a]=X("CreateRewardedInterstitialAdvert",a);await V();yd?a("Rewarded intersitial already exists"):(yd="ready",a(null,"Created rewarded interstitial"))};
U.ShowRewardedInterstitialAdvert=async(...a)=>{[,a]=X("ShowRewardedInterstitialAdvert",a);await V();"ready"!=yd?a("Cannot show rewarded interstitial"):(yd=null,a(null,"Rewarded interstitial shown"))};U.Configure=async(...a)=>{[,a]=X("Configure",a);await V();a(null,"PERSONALIZED&&true")};U.RequestConsent=async(...a)=>{[,a]=X("RequestConsent",a);await V();a(null,"PERSONALIZED&&true")};U.RequestIDFA=async(...a)=>{[,a]=X("RequestIDFA",a);await V();a(null,"authorized")};
self.C3MobileAdvertsAPI||(self.C3MobileAdvertsAPI={});self.C3MobileAdvertsAPI.fake=U;"use strict";const Y=self.Ya,Z={};let zd=!1,Ad=null;
const Bd=async a=>{if(!Z.webAdsScriptLoaded)return Y.v(a,"advert script not loaded, likely blocked by an ad blocker"),!1;zd||(self.adsbygoogle=self.adsbygoogle||[],self.adBreak=self.adConfig=b=>self.adsbygoogle.push(b),zd=!0);return Ad?Ad:Ad=new Promise(b=>{self.adConfig({preloadAdBreaks:"on",onReady:()=>b(!0)})})},Cd=()=>{Z.suspendRuntime&&Z.suspendRuntime()},Dd=()=>{Z.resumeRuntime&&Z.resumeRuntime()};Z.CreateBannerAdvert=async(a,b,c,d,e,f)=>{Y.v(f,"banner ads not supported in web platform")};
Z.ShowBannerAdvert=async a=>{Y.v(a,"banner ads not supported in web platform")};Z.HideBannerAdvert=async a=>{Y.v(a,"banner ads not supported in web platform")};Z.CreateInterstitialAdvert=async(a,b,c)=>{await Bd(c)&&Y.F(c,"interstitial ad created")};Z.ShowInterstitialAdvert=async a=>{await Bd(a)&&self.adBreak({type:"next",beforeAd:()=>Cd(),afterAd:()=>Dd(),adBreakDone:b=>{switch(b.breakStatus){case "viewed":case "dismissed":Y.F(a,"interstitial ad show");break;default:console.table(b),Y.v(a,"interstitial ad failed to show")}}})};
Z.CreateVideoAdvert=async(a,b,c)=>{Y.v(c,"video ads are deprecated")};Z.ShowVideoAdvert=async a=>{Y.v(a,"video ads are deprecated")};Z.CreateRewardedAdvert=async(a,b,c)=>{await Bd(c)&&Y.F(c,"rewarded ad created")};
Z.ShowRewardedAdvert=async a=>{await Bd(a)&&self.adBreak({type:"reward",beforeAd:()=>Cd(),afterAd:()=>Dd(),adBreakDone:b=>{switch(b.breakStatus){case "viewed":case "dismissed":Y.F(a,"rewarded ad show");break;case "ignored":Y.v(a,"rewarded ad ignored");break;default:console.table(b),Y.v(a,"rewarded ad failed to show")}},beforeReward:b=>{b()},adDismissed:()=>{Y.v(a,"closed with no reward")},adViewed:()=>{Y.F(a,JSON.stringify(["Reward",1]))}})};
Z.CreateRewardedInterstitialAdvert=async(a,b,c)=>{await Bd(c)&&Y.F(c,"rewarded interstitial ad created")};
Z.ShowRewardedInterstitialAdvert=async a=>{await Bd(a)&&self.adBreak({type:"reward",beforeAd:()=>Cd(),afterAd:()=>Dd(),adBreakDone:b=>{switch(b.breakStatus){case "viewed":case "dismissed":Y.F(a,"rewarded interstitial ad show");break;case "ignored":Y.v(a,"rewarded interstitial ad ignored");break;default:console.table(b),Y.v(a,"rewarded interstitial ad failed to show")}},beforeReward:b=>{b()},adDismissed:()=>{Y.v(a,"closed with no reward")},adViewed:()=>{Y.F(a,JSON.stringify(["Reward",1]))}})};
Z.Configure=async(a,b,c,d,e,f,g,h,l)=>{Z.webAdsScriptLoaded?Y.F(l,"UNKNOWN&&not-determined&&true"):Y.v(l,"advert script not loaded, likely blocked by an ad blocker")};Z.RequestConsent=async a=>{Y.F(a,"UNKNOWN&&not-determined&&true")};Z.SetMaxAdContentRating=async(a,b)=>{Y.v(b,"setting max ad content rating not supported in web platform")};Z.TagForChildDirectedTreatment=async(a,b)=>{Y.v(b,"tagging for children not supported in web platform")};Z.TagForUnderAgeOfConsent=async(a,b)=>{Y.v(b,"tagging for under age of consent not supported in web platform")};
Z.RequestIDFA=async a=>{Y.F(a,"not-determined")};Z.StatusUpdate=async(a,b,c)=>{Y.F(c,"UNKNOWN&&not-determined&&true")};self.C3MobileAdvertsAPI||(self.C3MobileAdvertsAPI={});self.C3MobileAdvertsAPI.web=Z;"use strict";let Ed=!1;
async function Fd(a,b,c){const d=Gd();d.suspendRuntime||(d.suspendRuntime=()=>{a.u.nb("runtime","visibilitychange",{hidden:!0})});d.resumeRuntime||(d.resumeRuntime=()=>{a.u.nb("runtime","visibilitychange",{hidden:!1})});if(!d)throw Ed||(Ed=!0,console.warn("The Mobile Advert plugin is not loaded. Please note that it only works in Android or iOS exports")),Error("advert plugin not loaded");return new Promise((e,f)=>{(0,d[b])(...c,(g,h)=>{g?f(g):e(h)})})}
async function Hd(a,b=null){const c=Gd();c.webAdsScriptLoaded=!1;return new Promise(d=>{const e=document.createElement("script");if(b)for(let f in b)e.setAttribute(f,b[f]);e.onload=function(){c.webAdsScriptLoaded=!0;d()};e.onerror=function(){c.webAdsScriptLoaded=!1;d()};e.src=a;document.head.appendChild(e)})}function Gd(){if(self.cordova)return self.C3MobileAdvertsAPI.real;if(!self.cordova)return self.C3MobileAdvertsAPI.web}
self.Ra.Hb(class extends self.lb{constructor(a){super(a,"advert");a=b=>[b,c=>Fd(this,b,c)];ca(this,[a("CreateBannerAdvert"),a("ShowBannerAdvert"),a("HideBannerAdvert"),a("CreateInterstitialAdvert"),a("ShowInterstitialAdvert"),a("CreateVideoAdvert"),a("ShowVideoAdvert"),a("CreateRewardedAdvert"),a("ShowRewardedAdvert"),a("CreateRewardedInterstitialAdvert"),a("ShowRewardedInterstitialAdvert"),a("Configure"),a("RequestConsent"),a("SetUserPersonalisation"),a("SetMaxAdContentRating"),a("TagForChildDirectedTreatment"),
a("TagForUnderAgeOfConsent"),a("RequestIDFA"),a("StatusUpdate"),(b=>[b,c=>Hd(c[0],c[1])])("AddScript")])}});
