const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Arr,
		C3.Plugins.AdvancedRandom,
		C3.Behaviors.Timer,
		C3.Plugins.LocalStorage,
		C3.Plugins.Button,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Cnds.CompareX,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Particles.Acts.SetTimeout,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Cnds.CompareY,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.AdvancedRandom.Exps.Weighted,
		C3.Plugins.System.Exps.left,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Particles.Acts.SetX,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.Timer.Exps.TotalTime,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue
	];
};
self.C3_JsPropNameTable = [
	{IMG_Aposta: 0},
	{Local: 0},
	{Tween: 0},
	{TXTInfo: 0},
	{Ativo: 0},
	{BTN_Auto: 0},
	{BTN_Aposta: 0},
	{Mouse: 0},
	{Hud_Auto: 0},
	{Quantidade: 0},
	{BTN_Option_Auto: 0},
	{TXT_Atumotatico: 0},
	{Touch: 0},
	{IMG_infinto: 0},
	{TXT_Infinito: 0},
	{BTN_CancelAuto: 0},
	{BTN_Valor: 0},
	{Hud_Valor: 0},
	{BTN_Option_Valor: 0},
	{Hud_Stop: 0},
	{BTN_Stop: 0},
	{BTN_Option_Stop: 0},
	{IMG_BG: 0},
	{EfeitoLuz: 0},
	{Sine: 0},
	{Sine2: 0},
	{Foguete: 0},
	{Fire_foguete: 0},
	{Particles: 0},
	{Particles2: 0},
	{IMG_Rastrofoguete: 0},
	{OBJ_Historico: 0},
	{Customize: 0},
	{TXT_HistoricoMultiplicador: 0},
	{Historico_Mul_X: 0},
	{AdvancedRandom: 0},
	{Timer: 0},
	{TXT_Partida: 0},
	{IMG_Explosion: 0},
	{LocalStorage: 0},
	{local: 0},
	{BG_LoadBar: 0},
	{volume: 0},
	{tamanho: 0},
	{LoadBar: 0},
	{Particles3: 0},
	{Text: 0},
	{TxT_Historico: 0},
	{"0_Historico": 0},
	{Particles4: 0},
	{Particles5: 0},
	{"0_Dados": 0},
	{Particles6: 0},
	{clarkvr: 0},
	{Text_error_api: 0},
	{BTNExit: 0},
	{Navegador: 0},
	{bt_home: 0},
	{Keyboard: 0},
	{Tile_Grade: 0},
	{rect: 0},
	{BTN_Historico: 0},
	{HUD_Historico: 0},
	{Audio: 0},
	{Hud_Money: 0},
	{BTN_Sound: 0},
	{Buttons: 0},
	{EffectHover: 0},
	{timer_animations: 0},
	{Auto_Manual: 0},
	{QTD_Auto: 0},
	{Retirada: 0},
	{ValorSalvo: 0},
	{Stop: 0},
	{Jogando: 0},
	{Money_Efeito: 0},
	{Dif: 0},
	{Adicionando_Removendo: 0},
	{Sound: 0},
	{Money: 0},
	{ValorAposta: 0},
	{Valor: 0},
	{L: 0},
	{Text_money: 0},
	{timer: 0},
	{transform: 0},
	{Multiplicador: 0},
	{x_valor: 0},
	{y_valor: 0},
	{chance: 0},
	{transfor_text: 0},
	{Partida: 0},
	{Game_Mult: 0},
	{Round_Partida: 0},
	{Cal: 0},
	{v: 0}
];

self.InstanceType = {
	IMG_Aposta: class extends self.ISpriteInstance {},
	TXTInfo: class extends self.ITextInstance {},
	BTN_Auto: class extends self.ISpriteInstance {},
	BTN_Aposta: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Hud_Auto: class extends self.ISpriteInstance {},
	BTN_Option_Auto: class extends self.ISpriteInstance {},
	TXT_Atumotatico: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	IMG_infinto: class extends self.ISpriteInstance {},
	TXT_Infinito: class extends self.ITextInstance {},
	BTN_CancelAuto: class extends self.ISpriteInstance {},
	BTN_Valor: class extends self.ISpriteInstance {},
	Hud_Valor: class extends self.ISpriteInstance {},
	BTN_Option_Valor: class extends self.ISpriteInstance {},
	Hud_Stop: class extends self.ISpriteInstance {},
	BTN_Stop: class extends self.ISpriteInstance {},
	BTN_Option_Stop: class extends self.ISpriteInstance {},
	IMG_BG: class extends self.ISpriteInstance {},
	EfeitoLuz: class extends self.ISpriteInstance {},
	Foguete: class extends self.ISpriteInstance {},
	Fire_foguete: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	IMG_Rastrofoguete: class extends self.ITiledBackgroundInstance {},
	OBJ_Historico: class extends self.ISpriteInstance {},
	TXT_HistoricoMultiplicador: class extends self.ITextInstance {},
	Historico_Mul_X: class extends self.IArrayInstance {},
	AdvancedRandom: class extends self.IInstance {},
	TXT_Partida: class extends self.ITextInstance {},
	IMG_Explosion: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	BG_LoadBar: class extends self.ITiledBackgroundInstance {},
	LoadBar: class extends self.ITiledBackgroundInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Text: class extends self.ITextInstance {},
	TxT_Historico: class extends self.ITextInstance {},
	_0_Historico: class extends self.IArrayInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Particles5: class extends self.IParticlesInstance {},
	_0_Dados: class extends self.IArrayInstance {},
	Particles6: class extends self.IParticlesInstance {},
	clarkvr: class extends self.ISpriteInstance {},
	Text_error_api: class extends self.ITextInstance {},
	BTNExit: class extends self.IButtonInstance {},
	Navegador: class extends self.IInstance {},
	bt_home: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Tile_Grade: class extends self.ITiledBackgroundInstance {},
	rect: class extends self.ISpriteInstance {},
	BTN_Historico: class extends self.ISpriteInstance {},
	HUD_Historico: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Hud_Money: class extends self.ISpriteInstance {},
	BTN_Sound: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}